// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type ActivateEndpointRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Endpoint ID
	EndpointID string `pathParam:"style=simple,explode=false,name=endpointID"`
}

func (a *ActivateEndpointRequest) GetProjectID() string {
	if a == nil {
		return ""
	}
	return a.ProjectID
}

func (a *ActivateEndpointRequest) GetEndpointID() string {
	if a == nil {
		return ""
	}
	return a.EndpointID
}

// ActivateEndpointNotFoundError - Not Found
type ActivateEndpointNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ActivateEndpointNotFoundError{}

func (e *ActivateEndpointNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ActivateEndpointUnauthorizedError - Unauthorized
type ActivateEndpointUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ActivateEndpointUnauthorizedError{}

func (e *ActivateEndpointUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ActivateEndpointBadRequestError - Bad Request
type ActivateEndpointBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ActivateEndpointBadRequestError{}

func (e *ActivateEndpointBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ActivateEndpointResponseBody - Accepted
type ActivateEndpointResponseBody struct {
	Message *string           `json:"message,omitempty"`
	Status  *bool             `json:"status,omitempty"`
	Data    *EndpointResponse `json:"data,omitempty"`
}

func (a *ActivateEndpointResponseBody) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *ActivateEndpointResponseBody) GetStatus() *bool {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *ActivateEndpointResponseBody) GetData() *EndpointResponse {
	if a == nil {
		return nil
	}
	return a.Data
}

type ActivateEndpointResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Accepted
	Object *ActivateEndpointResponseBody
}

func (a *ActivateEndpointResponse) GetHTTPMeta() HTTPMetadata {
	if a == nil {
		return HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ActivateEndpointResponse) GetObject() *ActivateEndpointResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
