// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type AlertConfiguration struct {
	// Count
	Count *int64 `json:"count,omitempty"`
	// Threshold
	Threshold *string `json:"threshold,omitempty"`
}

func (o *AlertConfiguration) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *AlertConfiguration) GetThreshold() *string {
	if o == nil {
		return nil
	}
	return o.Threshold
}
