// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type AmqpAuth struct {
	Password *string `json:"password,omitempty"`
	User     *string `json:"user,omitempty"`
}

func (o *AmqpAuth) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *AmqpAuth) GetUser() *string {
	if o == nil {
		return nil
	}
	return o.User
}
