// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type AmqpPubSubconfig struct {
	Auth               *AmqpAuth     `json:"auth,omitempty"`
	BindExchange       *AmqpExchange `json:"bindExchange,omitempty"`
	DeadLetterExchange *string       `json:"deadLetterExchange,omitempty"`
	Host               *string       `json:"host,omitempty"`
	Port               *string       `json:"port,omitempty"`
	Queue              *string       `json:"queue,omitempty"`
	Schema             *string       `json:"schema,omitempty"`
	Vhost              *string       `json:"vhost,omitempty"`
}

func (a *AmqpPubSubconfig) GetAuth() *AmqpAuth {
	if a == nil {
		return nil
	}
	return a.Auth
}

func (a *AmqpPubSubconfig) GetBindExchange() *AmqpExchange {
	if a == nil {
		return nil
	}
	return a.BindExchange
}

func (a *AmqpPubSubconfig) GetDeadLetterExchange() *string {
	if a == nil {
		return nil
	}
	return a.DeadLetterExchange
}

func (a *AmqpPubSubconfig) GetHost() *string {
	if a == nil {
		return nil
	}
	return a.Host
}

func (a *AmqpPubSubconfig) GetPort() *string {
	if a == nil {
		return nil
	}
	return a.Port
}

func (a *AmqpPubSubconfig) GetQueue() *string {
	if a == nil {
		return nil
	}
	return a.Queue
}

func (a *AmqpPubSubconfig) GetSchema() *string {
	if a == nil {
		return nil
	}
	return a.Schema
}

func (a *AmqpPubSubconfig) GetVhost() *string {
	if a == nil {
		return nil
	}
	return a.Vhost
}
