// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type AmqpExchange struct {
	Exchange   *string `json:"exchange,omitempty"`
	RoutingKey *string `json:"routingKey,omitempty"`
}

func (a *AmqpExchange) GetExchange() *string {
	if a == nil {
		return nil
	}
	return a.Exchange
}

func (a *AmqpExchange) GetRoutingKey() *string {
	if a == nil {
		return nil
	}
	return a.RoutingKey
}
