// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type AmqpAuth struct {
	Password *string `json:"password,omitempty"`
	User     *string `json:"user,omitempty"`
}

func (a *AmqpAuth) GetPassword() *string {
	if a == nil {
		return nil
	}
	return a.Password
}

func (a *AmqpAuth) GetUser() *string {
	if a == nil {
		return nil
	}
	return a.User
}
