// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type APIKey struct {
	HeaderName  string `json:"header_name"`
	HeaderValue string `json:"header_value"`
}

func (o *APIKey) GetHeaderName() string {
	if o == nil {
		return ""
	}
	return o.HeaderName
}

func (o *APIKey) GetHeaderValue() string {
	if o == nil {
		return ""
	}
	return o.HeaderValue
}
