// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e5092d46c19c

package convoy

type APIKey struct {
	HeaderName  string `json:"header_name"`
	HeaderValue string `json:"header_value"`
}

func (a *APIKey) GetHeaderName() string {
	if a == nil {
		return ""
	}
	return a.HeaderName
}

func (a *APIKey) GetHeaderValue() string {
	if a == nil {
		return ""
	}
	return a.HeaderValue
}
