// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 95de0aea1a38

package convoy

type BasicAuth struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

func (b *BasicAuth) GetPassword() string {
	if b == nil {
		return ""
	}
	return b.Password
}

func (b *BasicAuth) GetUsername() string {
	if b == nil {
		return ""
	}
	return b.Username
}
