// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type BasicAuth struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

func (o *BasicAuth) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *BasicAuth) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
