// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type BatchReplayEventsDirection string

const (
	BatchReplayEventsDirectionNext BatchReplayEventsDirection = "next"
	BatchReplayEventsDirectionPrev BatchReplayEventsDirection = "prev"
)

func (e BatchReplayEventsDirection) ToPointer() *BatchReplayEventsDirection {
	return &e
}
func (e *BatchReplayEventsDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "next":
		fallthrough
	case "prev":
		*e = BatchReplayEventsDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchReplayEventsDirection: %v", v)
	}
}

type BatchReplayEventsRequest struct {
	// Project ID
	ProjectID string                      `pathParam:"style=simple,explode=false,name=projectID"`
	Direction *BatchReplayEventsDirection `queryParam:"style=form,explode=true,name=direction"`
	// The end date
	EndDate *string `queryParam:"style=form,explode=true,name=endDate"`
	// A list of endpoint ids to filter by
	EndpointID []string `queryParam:"style=form,explode=true,name=endpointId"`
	// IdempotencyKey to filter by
	IdempotencyKey *string `queryParam:"style=form,explode=true,name=idempotencyKey"`
	// A pagination cursor to fetch the next page of a list
	NextPageCursor *string `queryParam:"style=form,explode=true,name=next_page_cursor"`
	// The number of items to return per page
	PerPage *int64 `queryParam:"style=form,explode=true,name=perPage"`
	// A pagination cursor to fetch the previous page of a list
	PrevPageCursor *string `queryParam:"style=form,explode=true,name=prev_page_cursor"`
	// Any arbitrary value to filter the events payload
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Sort order, values are `ASC` or `DESC`, defaults to `DESC`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// A list of Source IDs to filter the events by.
	SourceID []string `queryParam:"style=form,explode=true,name=sourceId"`
	// The start date
	StartDate *string `queryParam:"style=form,explode=true,name=startDate"`
}

func (b *BatchReplayEventsRequest) GetProjectID() string {
	if b == nil {
		return ""
	}
	return b.ProjectID
}

func (b *BatchReplayEventsRequest) GetDirection() *BatchReplayEventsDirection {
	if b == nil {
		return nil
	}
	return b.Direction
}

func (b *BatchReplayEventsRequest) GetEndDate() *string {
	if b == nil {
		return nil
	}
	return b.EndDate
}

func (b *BatchReplayEventsRequest) GetEndpointID() []string {
	if b == nil {
		return nil
	}
	return b.EndpointID
}

func (b *BatchReplayEventsRequest) GetIdempotencyKey() *string {
	if b == nil {
		return nil
	}
	return b.IdempotencyKey
}

func (b *BatchReplayEventsRequest) GetNextPageCursor() *string {
	if b == nil {
		return nil
	}
	return b.NextPageCursor
}

func (b *BatchReplayEventsRequest) GetPerPage() *int64 {
	if b == nil {
		return nil
	}
	return b.PerPage
}

func (b *BatchReplayEventsRequest) GetPrevPageCursor() *string {
	if b == nil {
		return nil
	}
	return b.PrevPageCursor
}

func (b *BatchReplayEventsRequest) GetQuery() *string {
	if b == nil {
		return nil
	}
	return b.Query
}

func (b *BatchReplayEventsRequest) GetSort() *string {
	if b == nil {
		return nil
	}
	return b.Sort
}

func (b *BatchReplayEventsRequest) GetSourceID() []string {
	if b == nil {
		return nil
	}
	return b.SourceID
}

func (b *BatchReplayEventsRequest) GetStartDate() *string {
	if b == nil {
		return nil
	}
	return b.StartDate
}

// BatchReplayEventsNotFoundError - Not Found
type BatchReplayEventsNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BatchReplayEventsNotFoundError{}

func (e *BatchReplayEventsNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BatchReplayEventsUnauthorizedError - Unauthorized
type BatchReplayEventsUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BatchReplayEventsUnauthorizedError{}

func (e *BatchReplayEventsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BatchReplayEventsBadRequestError - Bad Request
type BatchReplayEventsBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BatchReplayEventsBadRequestError{}

func (e *BatchReplayEventsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BatchReplayEventsResponseBody - OK
type BatchReplayEventsResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *string `json:"data,omitempty"`
}

func (b *BatchReplayEventsResponseBody) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BatchReplayEventsResponseBody) GetStatus() *bool {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *BatchReplayEventsResponseBody) GetData() *string {
	if b == nil {
		return nil
	}
	return b.Data
}

type BatchReplayEventsResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *BatchReplayEventsResponseBody
}

func (b *BatchReplayEventsResponse) GetHTTPMeta() HTTPMetadata {
	if b == nil {
		return HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BatchReplayEventsResponse) GetObject() *BatchReplayEventsResponseBody {
	if b == nil {
		return nil
	}
	return b.Object
}
