// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type BulkUpdateFilterRequest struct {
	Body      map[string]any `json:"body,omitempty"`
	EventType *string        `json:"event_type,omitempty"`
	Headers   map[string]any `json:"headers,omitempty"`
	UID       string         `json:"uid"`
}

func (o *BulkUpdateFilterRequest) GetBody() map[string]any {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *BulkUpdateFilterRequest) GetEventType() *string {
	if o == nil {
		return nil
	}
	return o.EventType
}

func (o *BulkUpdateFilterRequest) GetHeaders() map[string]any {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *BulkUpdateFilterRequest) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}
