// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type BulkUpdateFiltersRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
	// Filters to update
	RequestBody []BulkUpdateFilterRequest `request:"mediaType=application/json"`
}

func (b *BulkUpdateFiltersRequest) GetProjectID() string {
	if b == nil {
		return ""
	}
	return b.ProjectID
}

func (b *BulkUpdateFiltersRequest) GetSubscriptionID() string {
	if b == nil {
		return ""
	}
	return b.SubscriptionID
}

func (b *BulkUpdateFiltersRequest) GetRequestBody() []BulkUpdateFilterRequest {
	if b == nil {
		return []BulkUpdateFilterRequest{}
	}
	return b.RequestBody
}

// BulkUpdateFiltersNotFoundError - Not Found
type BulkUpdateFiltersNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BulkUpdateFiltersNotFoundError{}

func (e *BulkUpdateFiltersNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BulkUpdateFiltersUnauthorizedError - Unauthorized
type BulkUpdateFiltersUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BulkUpdateFiltersUnauthorizedError{}

func (e *BulkUpdateFiltersUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BulkUpdateFiltersBadRequestError - Bad Request
type BulkUpdateFiltersBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BulkUpdateFiltersBadRequestError{}

func (e *BulkUpdateFiltersBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BulkUpdateFiltersResponseBody - OK
type BulkUpdateFiltersResponseBody struct {
	Message *string          `json:"message,omitempty"`
	Status  *bool            `json:"status,omitempty"`
	Data    []FilterResponse `json:"data,omitempty"`
}

func (b *BulkUpdateFiltersResponseBody) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BulkUpdateFiltersResponseBody) GetStatus() *bool {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *BulkUpdateFiltersResponseBody) GetData() []FilterResponse {
	if b == nil {
		return nil
	}
	return b.Data
}

type BulkUpdateFiltersResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *BulkUpdateFiltersResponseBody
}

func (b *BulkUpdateFiltersResponse) GetHTTPMeta() HTTPMetadata {
	if b == nil {
		return HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkUpdateFiltersResponse) GetObject() *BulkUpdateFiltersResponseBody {
	if b == nil {
		return nil
	}
	return b.Object
}
