// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type BulkCreateFiltersRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
	// Filters to create
	RequestBody []CreateFilterRequest `request:"mediaType=application/json"`
}

func (b *BulkCreateFiltersRequest) GetProjectID() string {
	if b == nil {
		return ""
	}
	return b.ProjectID
}

func (b *BulkCreateFiltersRequest) GetSubscriptionID() string {
	if b == nil {
		return ""
	}
	return b.SubscriptionID
}

func (b *BulkCreateFiltersRequest) GetRequestBody() []CreateFilterRequest {
	if b == nil {
		return []CreateFilterRequest{}
	}
	return b.RequestBody
}

// BulkCreateFiltersNotFoundError - Not Found
type BulkCreateFiltersNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BulkCreateFiltersNotFoundError{}

func (e *BulkCreateFiltersNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BulkCreateFiltersUnauthorizedError - Unauthorized
type BulkCreateFiltersUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BulkCreateFiltersUnauthorizedError{}

func (e *BulkCreateFiltersUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BulkCreateFiltersBadRequestError - Bad Request
type BulkCreateFiltersBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &BulkCreateFiltersBadRequestError{}

func (e *BulkCreateFiltersBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BulkCreateFiltersResponseBody - Created
type BulkCreateFiltersResponseBody struct {
	Message *string          `json:"message,omitempty"`
	Status  *bool            `json:"status,omitempty"`
	Data    []FilterResponse `json:"data,omitempty"`
}

func (b *BulkCreateFiltersResponseBody) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BulkCreateFiltersResponseBody) GetStatus() *bool {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *BulkCreateFiltersResponseBody) GetData() []FilterResponse {
	if b == nil {
		return nil
	}
	return b.Data
}

type BulkCreateFiltersResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *BulkCreateFiltersResponseBody
}

func (b *BulkCreateFiltersResponse) GetHTTPMeta() HTTPMetadata {
	if b == nil {
		return HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkCreateFiltersResponse) GetObject() *BulkCreateFiltersResponseBody {
	if b == nil {
		return nil
	}
	return b.Object
}
