// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type BulkUpdateFilterRequest struct {
	Body      map[string]any `json:"body,omitempty"`
	EventType *string        `json:"event_type,omitempty"`
	Headers   map[string]any `json:"headers,omitempty"`
	UID       string         `json:"uid"`
}

func (b *BulkUpdateFilterRequest) GetBody() map[string]any {
	if b == nil {
		return nil
	}
	return b.Body
}

func (b *BulkUpdateFilterRequest) GetEventType() *string {
	if b == nil {
		return nil
	}
	return b.EventType
}

func (b *BulkUpdateFilterRequest) GetHeaders() map[string]any {
	if b == nil {
		return nil
	}
	return b.Headers
}

func (b *BulkUpdateFilterRequest) GetUID() string {
	if b == nil {
		return ""
	}
	return b.UID
}
