// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type CLIMetadata struct {
	EventType *string `json:"event_type,omitempty"`
	SourceID  *string `json:"source_id,omitempty"`
}

func (c *CLIMetadata) GetEventType() *string {
	if c == nil {
		return nil
	}
	return c.EventType
}

func (c *CLIMetadata) GetSourceID() *string {
	if c == nil {
		return nil
	}
	return c.SourceID
}
