// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreatePortalLinkRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Portal Link Details
	PortalLink PortalLink `request:"mediaType=application/json"`
}

func (o *CreatePortalLinkRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreatePortalLinkRequest) GetPortalLink() PortalLink {
	if o == nil {
		return PortalLink{}
	}
	return o.PortalLink
}

// CreatePortalLinkNotFoundError - Not Found
type CreatePortalLinkNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreatePortalLinkNotFoundError{}

func (e *CreatePortalLinkNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreatePortalLinkUnauthorizedError - Unauthorized
type CreatePortalLinkUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreatePortalLinkUnauthorizedError{}

func (e *CreatePortalLinkUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreatePortalLinkBadRequestError - Bad Request
type CreatePortalLinkBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreatePortalLinkBadRequestError{}

func (e *CreatePortalLinkBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreatePortalLinkResponseBody - Created
type CreatePortalLinkResponseBody struct {
	Message *string             `json:"message,omitempty"`
	Status  *bool               `json:"status,omitempty"`
	Data    *PortalLinkResponse `json:"data,omitempty"`
}

func (o *CreatePortalLinkResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreatePortalLinkResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreatePortalLinkResponseBody) GetData() *PortalLinkResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreatePortalLinkResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreatePortalLinkResponseBody
}

func (o *CreatePortalLinkResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePortalLinkResponse) GetObject() *CreatePortalLinkResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
