// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

// CreateEventData - Data is an arbitrary JSON value that gets sent as the body of the
// webhook to the endpoints
type CreateEventData struct {
}

type CreateEvent struct {
	// Deprecated but necessary for backward compatibility.
	AppID *string `json:"app_id,omitempty"`
	// Specifies custom headers you want convoy to add when the event is dispatched to your endpoint
	CustomHeaders map[string]string `json:"custom_headers,omitempty"`
	// Data is an arbitrary JSON value that gets sent as the body of the
	// webhook to the endpoints
	Data *CreateEventData `json:"data,omitempty"`
	// Specifies the endpoint to send this event to.
	EndpointID *string `json:"endpoint_id,omitempty"`
	// Event Type is used for filtering and debugging e.g invoice.paid
	EventType *string `json:"event_type,omitempty"`
	// Specify a key for event deduplication
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
}

func (c *CreateEvent) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateEvent) GetCustomHeaders() map[string]string {
	if c == nil {
		return nil
	}
	return c.CustomHeaders
}

func (c *CreateEvent) GetData() *CreateEventData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateEvent) GetEndpointID() *string {
	if c == nil {
		return nil
	}
	return c.EndpointID
}

func (c *CreateEvent) GetEventType() *string {
	if c == nil {
		return nil
	}
	return c.EventType
}

func (c *CreateEvent) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}
