// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateFilterRequestRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
	// Filter to create
	CreateFilterRequest CreateFilterRequest `request:"mediaType=application/json"`
}

func (o *CreateFilterRequestRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateFilterRequestRequest) GetSubscriptionID() string {
	if o == nil {
		return ""
	}
	return o.SubscriptionID
}

func (o *CreateFilterRequestRequest) GetCreateFilterRequest() CreateFilterRequest {
	if o == nil {
		return CreateFilterRequest{}
	}
	return o.CreateFilterRequest
}

// CreateFilterNotFoundError - Not Found
type CreateFilterNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateFilterNotFoundError{}

func (e *CreateFilterNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateFilterUnauthorizedError - Unauthorized
type CreateFilterUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateFilterUnauthorizedError{}

func (e *CreateFilterUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateFilterBadRequestError - Bad Request
type CreateFilterBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateFilterBadRequestError{}

func (e *CreateFilterBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateFilterResponseBody - Created
type CreateFilterResponseBody struct {
	Message *string         `json:"message,omitempty"`
	Status  *bool           `json:"status,omitempty"`
	Data    *FilterResponse `json:"data,omitempty"`
}

func (o *CreateFilterResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateFilterResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateFilterResponseBody) GetData() *FilterResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateFilterResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreateFilterResponseBody
}

func (o *CreateFilterResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateFilterResponse) GetObject() *CreateFilterResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
