// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type CreateFilterRequest struct {
	// Body matching criteria (optional)
	Body map[string]any `json:"body,omitempty"`
	// Type of event this filter applies to (required)
	EventType string `json:"event_type"`
	// Header matching criteria (optional)
	Headers map[string]any `json:"headers,omitempty"`
}

func (c *CreateFilterRequest) GetBody() map[string]any {
	if c == nil {
		return nil
	}
	return c.Body
}

func (c *CreateFilterRequest) GetEventType() string {
	if c == nil {
		return ""
	}
	return c.EventType
}

func (c *CreateFilterRequest) GetHeaders() map[string]any {
	if c == nil {
		return nil
	}
	return c.Headers
}
