// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type CreateEventType struct {
	// Category is a product-specific grouping for the event type
	Category *string `json:"category,omitempty"`
	// Description is used to describe what the event type does
	Description *string `json:"description,omitempty"`
	// JSONSchema is the JSON structure of the event type
	JSONSchema map[string]any `json:"json_schema,omitempty"`
	// Name is the event type name. E.g., invoice.created
	Name *string `json:"name,omitempty"`
}

func (c *CreateEventType) GetCategory() *string {
	if c == nil {
		return nil
	}
	return c.Category
}

func (c *CreateEventType) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateEventType) GetJSONSchema() map[string]any {
	if c == nil {
		return nil
	}
	return c.JSONSchema
}

func (c *CreateEventType) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}
