// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateEndpointRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Endpoint Details
	CreateEndpoint CreateEndpoint `request:"mediaType=application/json"`
}

func (c *CreateEndpointRequest) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CreateEndpointRequest) GetCreateEndpoint() CreateEndpoint {
	if c == nil {
		return CreateEndpoint{}
	}
	return c.CreateEndpoint
}

// CreateEndpointNotFoundError - Not Found
type CreateEndpointNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointNotFoundError{}

func (e *CreateEndpointNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointUnauthorizedError - Unauthorized
type CreateEndpointUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointUnauthorizedError{}

func (e *CreateEndpointUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointBadRequestError - Bad Request
type CreateEndpointBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointBadRequestError{}

func (e *CreateEndpointBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointResponseBody - Created
type CreateEndpointResponseBody struct {
	Message *string           `json:"message,omitempty"`
	Status  *bool             `json:"status,omitempty"`
	Data    *EndpointResponse `json:"data,omitempty"`
}

func (c *CreateEndpointResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateEndpointResponseBody) GetStatus() *bool {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreateEndpointResponseBody) GetData() *EndpointResponse {
	if c == nil {
		return nil
	}
	return c.Data
}

type CreateEndpointResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreateEndpointResponseBody
}

func (c *CreateEndpointResponse) GetHTTPMeta() HTTPMetadata {
	if c == nil {
		return HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEndpointResponse) GetObject() *CreateEndpointResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
