// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateEndpointFanoutEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Event Details
	FanoutEvent FanoutEvent `request:"mediaType=application/json"`
}

func (o *CreateEndpointFanoutEventRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateEndpointFanoutEventRequest) GetFanoutEvent() FanoutEvent {
	if o == nil {
		return FanoutEvent{}
	}
	return o.FanoutEvent
}

// CreateEndpointFanoutEventNotFoundError - Not Found
type CreateEndpointFanoutEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointFanoutEventNotFoundError{}

func (e *CreateEndpointFanoutEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointFanoutEventUnauthorizedError - Unauthorized
type CreateEndpointFanoutEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointFanoutEventUnauthorizedError{}

func (e *CreateEndpointFanoutEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointFanoutEventBadRequestError - Bad Request
type CreateEndpointFanoutEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointFanoutEventBadRequestError{}

func (e *CreateEndpointFanoutEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointFanoutEventResponseBody - Created
type CreateEndpointFanoutEventResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *Object `json:"data,omitempty"`
}

func (o *CreateEndpointFanoutEventResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateEndpointFanoutEventResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateEndpointFanoutEventResponseBody) GetData() *Object {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateEndpointFanoutEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreateEndpointFanoutEventResponseBody
}

func (o *CreateEndpointFanoutEventResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEndpointFanoutEventResponse) GetObject() *CreateEndpointFanoutEventResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
