// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateSourceRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Source Details
	CreateSource CreateSource `request:"mediaType=application/json"`
}

func (o *CreateSourceRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateSourceRequest) GetCreateSource() CreateSource {
	if o == nil {
		return CreateSource{}
	}
	return o.CreateSource
}

// CreateSourceNotFoundError - Not Found
type CreateSourceNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateSourceNotFoundError{}

func (e *CreateSourceNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateSourceUnauthorizedError - Unauthorized
type CreateSourceUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateSourceUnauthorizedError{}

func (e *CreateSourceUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateSourceBadRequestError - Bad Request
type CreateSourceBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateSourceBadRequestError{}

func (e *CreateSourceBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateSourceResponseBody - Created
type CreateSourceResponseBody struct {
	Message *string         `json:"message,omitempty"`
	Status  *bool           `json:"status,omitempty"`
	Data    *SourceResponse `json:"data,omitempty"`
}

func (o *CreateSourceResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateSourceResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateSourceResponseBody) GetData() *SourceResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateSourceResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreateSourceResponseBody
}

func (o *CreateSourceResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSourceResponse) GetObject() *CreateSourceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
