// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateBroadcastEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Broadcast Event Details
	BroadcastEvent BroadcastEvent `request:"mediaType=application/json"`
}

func (c *CreateBroadcastEventRequest) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CreateBroadcastEventRequest) GetBroadcastEvent() BroadcastEvent {
	if c == nil {
		return BroadcastEvent{}
	}
	return c.BroadcastEvent
}

// CreateBroadcastEventNotFoundError - Not Found
type CreateBroadcastEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateBroadcastEventNotFoundError{}

func (e *CreateBroadcastEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateBroadcastEventUnauthorizedError - Unauthorized
type CreateBroadcastEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateBroadcastEventUnauthorizedError{}

func (e *CreateBroadcastEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateBroadcastEventBadRequestError - Bad Request
type CreateBroadcastEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateBroadcastEventBadRequestError{}

func (e *CreateBroadcastEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateBroadcastEventResponseBody - Created
type CreateBroadcastEventResponseBody struct {
	Message *string        `json:"message,omitempty"`
	Status  *bool          `json:"status,omitempty"`
	Data    *EventResponse `json:"data,omitempty"`
}

func (c *CreateBroadcastEventResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateBroadcastEventResponseBody) GetStatus() *bool {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreateBroadcastEventResponseBody) GetData() *EventResponse {
	if c == nil {
		return nil
	}
	return c.Data
}

type CreateBroadcastEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreateBroadcastEventResponseBody
}

func (c *CreateBroadcastEventResponse) GetHTTPMeta() HTTPMetadata {
	if c == nil {
		return HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateBroadcastEventResponse) GetObject() *CreateBroadcastEventResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
