// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateEndpointEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Event Details
	CreateEvent CreateEvent `request:"mediaType=application/json"`
}

func (c *CreateEndpointEventRequest) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CreateEndpointEventRequest) GetCreateEvent() CreateEvent {
	if c == nil {
		return CreateEvent{}
	}
	return c.CreateEvent
}

// CreateEndpointEventNotFoundError - Not Found
type CreateEndpointEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointEventNotFoundError{}

func (e *CreateEndpointEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointEventUnauthorizedError - Unauthorized
type CreateEndpointEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointEventUnauthorizedError{}

func (e *CreateEndpointEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointEventBadRequestError - Bad Request
type CreateEndpointEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateEndpointEventBadRequestError{}

func (e *CreateEndpointEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateEndpointEventResponseBody - Created
type CreateEndpointEventResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *Object `json:"data,omitempty"`
}

func (c *CreateEndpointEventResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateEndpointEventResponseBody) GetStatus() *bool {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CreateEndpointEventResponseBody) GetData() *Object {
	if c == nil {
		return nil
	}
	return c.Data
}

type CreateEndpointEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *CreateEndpointEventResponseBody
}

func (c *CreateEndpointEventResponse) GetHTTPMeta() HTTPMetadata {
	if c == nil {
		return HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEndpointEventResponse) GetObject() *CreateEndpointEventResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
