// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type CreateEventType struct {
	// Category is a product-specific grouping for the event type
	Category *string `json:"category,omitempty"`
	// Description is used to describe what the event type does
	Description *string `json:"description,omitempty"`
	// JSONSchema is the JSON structure of the event type
	JSONSchema map[string]any `json:"json_schema,omitempty"`
	// Name is the event type name. E.g., invoice.created
	Name *string `json:"name,omitempty"`
}

func (o *CreateEventType) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *CreateEventType) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateEventType) GetJSONSchema() map[string]any {
	if o == nil {
		return nil
	}
	return o.JSONSchema
}

func (o *CreateEventType) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
