// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type CreateDynamicEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Event Details
	DynamicEvent DynamicEvent `request:"mediaType=application/json"`
}

func (c *CreateDynamicEventRequest) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CreateDynamicEventRequest) GetDynamicEvent() DynamicEvent {
	if c == nil {
		return DynamicEvent{}
	}
	return c.DynamicEvent
}

// CreateDynamicEventNotFoundError - Not Found
type CreateDynamicEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateDynamicEventNotFoundError{}

func (e *CreateDynamicEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateDynamicEventUnauthorizedError - Unauthorized
type CreateDynamicEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateDynamicEventUnauthorizedError{}

func (e *CreateDynamicEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateDynamicEventBadRequestError - Bad Request
type CreateDynamicEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &CreateDynamicEventBadRequestError{}

func (e *CreateDynamicEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type CreateDynamicEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *Object
}

func (c *CreateDynamicEventResponse) GetHTTPMeta() HTTPMetadata {
	if c == nil {
		return HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateDynamicEventResponse) GetObject() *Object {
	if c == nil {
		return nil
	}
	return c.Object
}
