// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

// CreateSubscriptionDeliveryMode - Delivery mode configuration
type CreateSubscriptionDeliveryMode string

const (
	CreateSubscriptionDeliveryModeAtLeastOnce CreateSubscriptionDeliveryMode = "at_least_once"
	CreateSubscriptionDeliveryModeAtMostOnce  CreateSubscriptionDeliveryMode = "at_most_once"
)

func (e CreateSubscriptionDeliveryMode) ToPointer() *CreateSubscriptionDeliveryMode {
	return &e
}

type CreateSubscription struct {
	// Alert configuration
	AlertConfig *AlertConfiguration `json:"alert_config,omitempty"`
	// Deprecated but necessary for backward compatibility
	AppID *string `json:"app_id,omitempty"`
	// Delivery mode configuration
	DeliveryMode *CreateSubscriptionDeliveryMode `json:"delivery_mode,omitempty"`
	// Destination endpoint ID
	EndpointID *string `json:"endpoint_id,omitempty"`
	// Filter configuration
	FilterConfig *FilterConfiguration `json:"filter_config,omitempty"`
	// Convoy supports mutating your request payload using a js function. Use this field
	// to specify a `transform` function for this purpose. See this[https://docs.getconvoy.io/product-manual/subscriptions#functions] for more
	Function *string `json:"function,omitempty"`
	// Subscription Nme
	Name *string `json:"name,omitempty"`
	// Rate limit configuration
	RateLimitConfig *RateLimitConfiguration `json:"rate_limit_config,omitempty"`
	// Source Id
	SourceID *string `json:"source_id,omitempty"`
}

func (o *CreateSubscription) GetAlertConfig() *AlertConfiguration {
	if o == nil {
		return nil
	}
	return o.AlertConfig
}

func (o *CreateSubscription) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreateSubscription) GetDeliveryMode() *CreateSubscriptionDeliveryMode {
	if o == nil {
		return nil
	}
	return o.DeliveryMode
}

func (o *CreateSubscription) GetEndpointID() *string {
	if o == nil {
		return nil
	}
	return o.EndpointID
}

func (o *CreateSubscription) GetFilterConfig() *FilterConfiguration {
	if o == nil {
		return nil
	}
	return o.FilterConfig
}

func (o *CreateSubscription) GetFunction() *string {
	if o == nil {
		return nil
	}
	return o.Function
}

func (o *CreateSubscription) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateSubscription) GetRateLimitConfig() *RateLimitConfiguration {
	if o == nil {
		return nil
	}
	return o.RateLimitConfig
}

func (o *CreateSubscription) GetSourceID() *string {
	if o == nil {
		return nil
	}
	return o.SourceID
}
