// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ebf71922c8d3

package convoy

type CustomResponse struct {
	Body        *string `json:"body,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
}

func (c *CustomResponse) GetBody() *string {
	if c == nil {
		return nil
	}
	return c.Body
}

func (c *CustomResponse) GetContentType() *string {
	if c == nil {
		return nil
	}
	return c.ContentType
}
