// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type DeleteSourceRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// source id
	SourceID string `pathParam:"style=simple,explode=false,name=sourceID"`
}

func (d *DeleteSourceRequest) GetProjectID() string {
	if d == nil {
		return ""
	}
	return d.ProjectID
}

func (d *DeleteSourceRequest) GetSourceID() string {
	if d == nil {
		return ""
	}
	return d.SourceID
}

// DeleteSourceNotFoundError - Not Found
type DeleteSourceNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeleteSourceNotFoundError{}

func (e *DeleteSourceNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteSourceUnauthorizedError - Unauthorized
type DeleteSourceUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeleteSourceUnauthorizedError{}

func (e *DeleteSourceUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteSourceBadRequestError - Bad Request
type DeleteSourceBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeleteSourceBadRequestError{}

func (e *DeleteSourceBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteSourceResponseBody - OK
type DeleteSourceResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *Object `json:"data,omitempty"`
}

func (d *DeleteSourceResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DeleteSourceResponseBody) GetStatus() *bool {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeleteSourceResponseBody) GetData() *Object {
	if d == nil {
		return nil
	}
	return d.Data
}

type DeleteSourceResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *DeleteSourceResponseBody
}

func (d *DeleteSourceResponse) GetHTTPMeta() HTTPMetadata {
	if d == nil {
		return HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteSourceResponse) GetObject() *DeleteSourceResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
