// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type DeleteFilterRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
	// Filter ID
	FilterID string `pathParam:"style=simple,explode=false,name=filterID"`
}

func (d *DeleteFilterRequest) GetProjectID() string {
	if d == nil {
		return ""
	}
	return d.ProjectID
}

func (d *DeleteFilterRequest) GetSubscriptionID() string {
	if d == nil {
		return ""
	}
	return d.SubscriptionID
}

func (d *DeleteFilterRequest) GetFilterID() string {
	if d == nil {
		return ""
	}
	return d.FilterID
}

// DeleteFilterNotFoundError - Not Found
type DeleteFilterNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeleteFilterNotFoundError{}

func (e *DeleteFilterNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteFilterUnauthorizedError - Unauthorized
type DeleteFilterUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeleteFilterUnauthorizedError{}

func (e *DeleteFilterUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteFilterBadRequestError - Bad Request
type DeleteFilterBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeleteFilterBadRequestError{}

func (e *DeleteFilterBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteFilterResponseBody - OK
type DeleteFilterResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *Object `json:"data,omitempty"`
}

func (d *DeleteFilterResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DeleteFilterResponseBody) GetStatus() *bool {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeleteFilterResponseBody) GetData() *Object {
	if d == nil {
		return nil
	}
	return d.Data
}

type DeleteFilterResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *DeleteFilterResponseBody
}

func (d *DeleteFilterResponse) GetHTTPMeta() HTTPMetadata {
	if d == nil {
		return HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteFilterResponse) GetObject() *DeleteFilterResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
