// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type DeliveryMode string

const (
	DeliveryModeAtLeastOnce DeliveryMode = "at_least_once"
	DeliveryModeAtMostOnce  DeliveryMode = "at_most_once"
)

func (e DeliveryMode) ToPointer() *DeliveryMode {
	return &e
}
