// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type DeliveryMode string

const (
	DeliveryModeAtLeastOnce DeliveryMode = "at_least_once"
	DeliveryModeAtMostOnce  DeliveryMode = "at_most_once"
)

func (e DeliveryMode) ToPointer() *DeliveryMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeliveryMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "at_least_once", "at_most_once":
			return true
		}
	}
	return false
}
