// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type DeliveryAttempt struct {
	APIVersion         *string           `json:"api_version,omitempty"`
	CreatedAt          *string           `json:"created_at,omitempty"`
	DeletedAt          *string           `json:"deleted_at,omitempty"`
	EndpointID         *string           `json:"endpoint_id,omitempty"`
	Error              *string           `json:"error,omitempty"`
	HTTPStatus         *string           `json:"http_status,omitempty"`
	IPAddress          *string           `json:"ip_address,omitempty"`
	Method             *string           `json:"method,omitempty"`
	MsgID              *string           `json:"msg_id,omitempty"`
	ProjectID          *string           `json:"project_id,omitempty"`
	RequestHTTPHeader  map[string]string `json:"request_http_header,omitempty"`
	ResponseData       *string           `json:"response_data,omitempty"`
	ResponseHTTPHeader map[string]string `json:"response_http_header,omitempty"`
	Status             *bool             `json:"status,omitempty"`
	UID                *string           `json:"uid,omitempty"`
	UpdatedAt          *string           `json:"updated_at,omitempty"`
	URL                *string           `json:"url,omitempty"`
}

func (o *DeliveryAttempt) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

func (o *DeliveryAttempt) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *DeliveryAttempt) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *DeliveryAttempt) GetEndpointID() *string {
	if o == nil {
		return nil
	}
	return o.EndpointID
}

func (o *DeliveryAttempt) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeliveryAttempt) GetHTTPStatus() *string {
	if o == nil {
		return nil
	}
	return o.HTTPStatus
}

func (o *DeliveryAttempt) GetIPAddress() *string {
	if o == nil {
		return nil
	}
	return o.IPAddress
}

func (o *DeliveryAttempt) GetMethod() *string {
	if o == nil {
		return nil
	}
	return o.Method
}

func (o *DeliveryAttempt) GetMsgID() *string {
	if o == nil {
		return nil
	}
	return o.MsgID
}

func (o *DeliveryAttempt) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *DeliveryAttempt) GetRequestHTTPHeader() map[string]string {
	if o == nil {
		return nil
	}
	return o.RequestHTTPHeader
}

func (o *DeliveryAttempt) GetResponseData() *string {
	if o == nil {
		return nil
	}
	return o.ResponseData
}

func (o *DeliveryAttempt) GetResponseHTTPHeader() map[string]string {
	if o == nil {
		return nil
	}
	return o.ResponseHTTPHeader
}

func (o *DeliveryAttempt) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *DeliveryAttempt) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *DeliveryAttempt) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *DeliveryAttempt) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
