// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type DeliveryAttempt struct {
	APIVersion         *string           `json:"api_version,omitempty"`
	CreatedAt          *string           `json:"created_at,omitempty"`
	DeletedAt          *string           `json:"deleted_at,omitempty"`
	EndpointID         *string           `json:"endpoint_id,omitempty"`
	Error              *string           `json:"error,omitempty"`
	HTTPStatus         *string           `json:"http_status,omitempty"`
	IPAddress          *string           `json:"ip_address,omitempty"`
	Method             *string           `json:"method,omitempty"`
	MsgID              *string           `json:"msg_id,omitempty"`
	ProjectID          *string           `json:"project_id,omitempty"`
	RequestHTTPHeader  map[string]string `json:"request_http_header,omitempty"`
	ResponseData       *string           `json:"response_data,omitempty"`
	ResponseHTTPHeader map[string]string `json:"response_http_header,omitempty"`
	Status             *bool             `json:"status,omitempty"`
	UID                *string           `json:"uid,omitempty"`
	UpdatedAt          *string           `json:"updated_at,omitempty"`
	URL                *string           `json:"url,omitempty"`
}

func (d *DeliveryAttempt) GetAPIVersion() *string {
	if d == nil {
		return nil
	}
	return d.APIVersion
}

func (d *DeliveryAttempt) GetCreatedAt() *string {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *DeliveryAttempt) GetDeletedAt() *string {
	if d == nil {
		return nil
	}
	return d.DeletedAt
}

func (d *DeliveryAttempt) GetEndpointID() *string {
	if d == nil {
		return nil
	}
	return d.EndpointID
}

func (d *DeliveryAttempt) GetError() *string {
	if d == nil {
		return nil
	}
	return d.Error
}

func (d *DeliveryAttempt) GetHTTPStatus() *string {
	if d == nil {
		return nil
	}
	return d.HTTPStatus
}

func (d *DeliveryAttempt) GetIPAddress() *string {
	if d == nil {
		return nil
	}
	return d.IPAddress
}

func (d *DeliveryAttempt) GetMethod() *string {
	if d == nil {
		return nil
	}
	return d.Method
}

func (d *DeliveryAttempt) GetMsgID() *string {
	if d == nil {
		return nil
	}
	return d.MsgID
}

func (d *DeliveryAttempt) GetProjectID() *string {
	if d == nil {
		return nil
	}
	return d.ProjectID
}

func (d *DeliveryAttempt) GetRequestHTTPHeader() map[string]string {
	if d == nil {
		return nil
	}
	return d.RequestHTTPHeader
}

func (d *DeliveryAttempt) GetResponseData() *string {
	if d == nil {
		return nil
	}
	return d.ResponseData
}

func (d *DeliveryAttempt) GetResponseHTTPHeader() map[string]string {
	if d == nil {
		return nil
	}
	return d.ResponseHTTPHeader
}

func (d *DeliveryAttempt) GetStatus() *bool {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeliveryAttempt) GetUID() *string {
	if d == nil {
		return nil
	}
	return d.UID
}

func (d *DeliveryAttempt) GetUpdatedAt() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}

func (d *DeliveryAttempt) GetURL() *string {
	if d == nil {
		return nil
	}
	return d.URL
}
