// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type DeprecateEventTypeRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Event Type ID
	EventTypeID string `pathParam:"style=simple,explode=false,name=eventTypeId"`
}

func (o *DeprecateEventTypeRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *DeprecateEventTypeRequest) GetEventTypeID() string {
	if o == nil {
		return ""
	}
	return o.EventTypeID
}

// DeprecateEventTypeNotFoundError - Not Found
type DeprecateEventTypeNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeprecateEventTypeNotFoundError{}

func (e *DeprecateEventTypeNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeprecateEventTypeUnauthorizedError - Unauthorized
type DeprecateEventTypeUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeprecateEventTypeUnauthorizedError{}

func (e *DeprecateEventTypeUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeprecateEventTypeBadRequestError - Bad Request
type DeprecateEventTypeBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &DeprecateEventTypeBadRequestError{}

func (e *DeprecateEventTypeBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeprecateEventTypeResponseBody - Created
type DeprecateEventTypeResponseBody struct {
	Message *string            `json:"message,omitempty"`
	Status  *bool              `json:"status,omitempty"`
	Data    *EventTypeResponse `json:"data,omitempty"`
}

func (o *DeprecateEventTypeResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *DeprecateEventTypeResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *DeprecateEventTypeResponseBody) GetData() *EventTypeResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type DeprecateEventTypeResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *DeprecateEventTypeResponseBody
}

func (o *DeprecateEventTypeResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeprecateEventTypeResponse) GetObject() *DeprecateEventTypeResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
