// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type Device struct {
	CreatedAt  *string       `json:"created_at,omitempty"`
	DeletedAt  *string       `json:"deleted_at,omitempty"`
	EndpointID *string       `json:"endpoint_id,omitempty"`
	HostName   *string       `json:"host_name,omitempty"`
	LastSeenAt *string       `json:"last_seen_at,omitempty"`
	ProjectID  *string       `json:"project_id,omitempty"`
	Status     *DeviceStatus `json:"status,omitempty"`
	UID        *string       `json:"uid,omitempty"`
	UpdatedAt  *string       `json:"updated_at,omitempty"`
}

func (d *Device) GetCreatedAt() *string {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *Device) GetDeletedAt() *string {
	if d == nil {
		return nil
	}
	return d.DeletedAt
}

func (d *Device) GetEndpointID() *string {
	if d == nil {
		return nil
	}
	return d.EndpointID
}

func (d *Device) GetHostName() *string {
	if d == nil {
		return nil
	}
	return d.HostName
}

func (d *Device) GetLastSeenAt() *string {
	if d == nil {
		return nil
	}
	return d.LastSeenAt
}

func (d *Device) GetProjectID() *string {
	if d == nil {
		return nil
	}
	return d.ProjectID
}

func (d *Device) GetStatus() *DeviceStatus {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *Device) GetUID() *string {
	if d == nil {
		return nil
	}
	return d.UID
}

func (d *Device) GetUpdatedAt() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}
