// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type DeviceStatus string

const (
	DeviceStatusOffline  DeviceStatus = "offline"
	DeviceStatusOnline   DeviceStatus = "online"
	DeviceStatusDisabled DeviceStatus = "disabled"
)

func (e DeviceStatus) ToPointer() *DeviceStatus {
	return &e
}
func (e *DeviceStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "offline":
		fallthrough
	case "online":
		fallthrough
	case "disabled":
		*e = DeviceStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeviceStatus: %v", v)
	}
}
