// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

// DynamicEventData - Data is an arbitrary JSON value that gets sent as the body of the
// webhook to the endpoints
type DynamicEventData struct {
}

type DynamicEvent struct {
	// Specifies custom headers you want convoy to add when the event is dispatched to your endpoint
	CustomHeaders map[string]string `json:"custom_headers,omitempty"`
	// Data is an arbitrary JSON value that gets sent as the body of the
	// webhook to the endpoints
	Data *DynamicEventData `json:"data,omitempty"`
	// Event Type is used for filtering and debugging e.g invoice.paid
	EventType *string `json:"event_type,omitempty"`
	// A list of event types for the subscription filter config
	EventTypes []string `json:"event_types,omitempty"`
	// Specify a key for event deduplication
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Endpoint's webhook secret. If not provided, Convoy autogenerates one for the endpoint.
	Secret *string `json:"secret,omitempty"`
	// URL is the endpoint's URL prefixed with https. non-https urls are currently
	// not supported.
	URL *string `json:"url,omitempty"`
}

func (d *DynamicEvent) GetCustomHeaders() map[string]string {
	if d == nil {
		return nil
	}
	return d.CustomHeaders
}

func (d *DynamicEvent) GetData() *DynamicEventData {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DynamicEvent) GetEventType() *string {
	if d == nil {
		return nil
	}
	return d.EventType
}

func (d *DynamicEvent) GetEventTypes() []string {
	if d == nil {
		return nil
	}
	return d.EventTypes
}

func (d *DynamicEvent) GetIdempotencyKey() *string {
	if d == nil {
		return nil
	}
	return d.IdempotencyKey
}

func (d *DynamicEvent) GetSecret() *string {
	if d == nil {
		return nil
	}
	return d.Secret
}

func (d *DynamicEvent) GetURL() *string {
	if d == nil {
		return nil
	}
	return d.URL
}
