// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type EndpointAuthenticationType string

const (
	EndpointAuthenticationTypeAPIKey EndpointAuthenticationType = "api_key"
)

func (e EndpointAuthenticationType) ToPointer() *EndpointAuthenticationType {
	return &e
}
func (e *EndpointAuthenticationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_key":
		*e = EndpointAuthenticationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EndpointAuthenticationType: %v", v)
	}
}
