// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type EndpointAuthentication struct {
	APIKey *APIKey                     `json:"api_key,omitempty"`
	Type   *EndpointAuthenticationType `json:"type,omitempty"`
}

func (o *EndpointAuthentication) GetAPIKey() *APIKey {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *EndpointAuthentication) GetType() *EndpointAuthenticationType {
	if o == nil {
		return nil
	}
	return o.Type
}
