// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type Endpoint struct {
	AdvancedSignatures *bool                   `json:"advanced_signatures,omitempty"`
	Authentication     *EndpointAuthentication `json:"authentication,omitempty"`
	CreatedAt          *string                 `json:"created_at,omitempty"`
	DeletedAt          *string                 `json:"deleted_at,omitempty"`
	Description        *string                 `json:"description,omitempty"`
	Events             *int64                  `json:"events,omitempty"`
	FailureRate        *float64                `json:"failure_rate,omitempty"`
	HTTPTimeout        *int64                  `json:"http_timeout,omitempty"`
	Name               *string                 `json:"name,omitempty"`
	OwnerID            *string                 `json:"owner_id,omitempty"`
	ProjectID          *string                 `json:"project_id,omitempty"`
	RateLimit          *int64                  `json:"rate_limit,omitempty"`
	RateLimitDuration  *int64                  `json:"rate_limit_duration,omitempty"`
	Secrets            []Secret                `json:"secrets,omitempty"`
	SlackWebhookURL    *string                 `json:"slack_webhook_url,omitempty"`
	Status             *EndpointStatus         `json:"status,omitempty"`
	SupportEmail       *string                 `json:"support_email,omitempty"`
	UID                *string                 `json:"uid,omitempty"`
	UpdatedAt          *string                 `json:"updated_at,omitempty"`
	URL                *string                 `json:"url,omitempty"`
}

func (o *Endpoint) GetAdvancedSignatures() *bool {
	if o == nil {
		return nil
	}
	return o.AdvancedSignatures
}

func (o *Endpoint) GetAuthentication() *EndpointAuthentication {
	if o == nil {
		return nil
	}
	return o.Authentication
}

func (o *Endpoint) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Endpoint) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *Endpoint) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Endpoint) GetEvents() *int64 {
	if o == nil {
		return nil
	}
	return o.Events
}

func (o *Endpoint) GetFailureRate() *float64 {
	if o == nil {
		return nil
	}
	return o.FailureRate
}

func (o *Endpoint) GetHTTPTimeout() *int64 {
	if o == nil {
		return nil
	}
	return o.HTTPTimeout
}

func (o *Endpoint) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Endpoint) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

func (o *Endpoint) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *Endpoint) GetRateLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.RateLimit
}

func (o *Endpoint) GetRateLimitDuration() *int64 {
	if o == nil {
		return nil
	}
	return o.RateLimitDuration
}

func (o *Endpoint) GetSecrets() []Secret {
	if o == nil {
		return nil
	}
	return o.Secrets
}

func (o *Endpoint) GetSlackWebhookURL() *string {
	if o == nil {
		return nil
	}
	return o.SlackWebhookURL
}

func (o *Endpoint) GetStatus() *EndpointStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Endpoint) GetSupportEmail() *string {
	if o == nil {
		return nil
	}
	return o.SupportEmail
}

func (o *Endpoint) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *Endpoint) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *Endpoint) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
