// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type Endpoint struct {
	AdvancedSignatures *bool                   `json:"advanced_signatures,omitempty"`
	Authentication     *EndpointAuthentication `json:"authentication,omitempty"`
	CreatedAt          *string                 `json:"created_at,omitempty"`
	DeletedAt          *string                 `json:"deleted_at,omitempty"`
	Description        *string                 `json:"description,omitempty"`
	Events             *int64                  `json:"events,omitempty"`
	FailureRate        *float64                `json:"failure_rate,omitempty"`
	HTTPTimeout        *int64                  `json:"http_timeout,omitempty"`
	Name               *string                 `json:"name,omitempty"`
	OwnerID            *string                 `json:"owner_id,omitempty"`
	ProjectID          *string                 `json:"project_id,omitempty"`
	RateLimit          *int64                  `json:"rate_limit,omitempty"`
	RateLimitDuration  *int64                  `json:"rate_limit_duration,omitempty"`
	Secrets            []Secret                `json:"secrets,omitempty"`
	SlackWebhookURL    *string                 `json:"slack_webhook_url,omitempty"`
	Status             *EndpointStatus         `json:"status,omitempty"`
	SupportEmail       *string                 `json:"support_email,omitempty"`
	UID                *string                 `json:"uid,omitempty"`
	UpdatedAt          *string                 `json:"updated_at,omitempty"`
	URL                *string                 `json:"url,omitempty"`
}

func (e *Endpoint) GetAdvancedSignatures() *bool {
	if e == nil {
		return nil
	}
	return e.AdvancedSignatures
}

func (e *Endpoint) GetAuthentication() *EndpointAuthentication {
	if e == nil {
		return nil
	}
	return e.Authentication
}

func (e *Endpoint) GetCreatedAt() *string {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *Endpoint) GetDeletedAt() *string {
	if e == nil {
		return nil
	}
	return e.DeletedAt
}

func (e *Endpoint) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *Endpoint) GetEvents() *int64 {
	if e == nil {
		return nil
	}
	return e.Events
}

func (e *Endpoint) GetFailureRate() *float64 {
	if e == nil {
		return nil
	}
	return e.FailureRate
}

func (e *Endpoint) GetHTTPTimeout() *int64 {
	if e == nil {
		return nil
	}
	return e.HTTPTimeout
}

func (e *Endpoint) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *Endpoint) GetOwnerID() *string {
	if e == nil {
		return nil
	}
	return e.OwnerID
}

func (e *Endpoint) GetProjectID() *string {
	if e == nil {
		return nil
	}
	return e.ProjectID
}

func (e *Endpoint) GetRateLimit() *int64 {
	if e == nil {
		return nil
	}
	return e.RateLimit
}

func (e *Endpoint) GetRateLimitDuration() *int64 {
	if e == nil {
		return nil
	}
	return e.RateLimitDuration
}

func (e *Endpoint) GetSecrets() []Secret {
	if e == nil {
		return nil
	}
	return e.Secrets
}

func (e *Endpoint) GetSlackWebhookURL() *string {
	if e == nil {
		return nil
	}
	return e.SlackWebhookURL
}

func (e *Endpoint) GetStatus() *EndpointStatus {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *Endpoint) GetSupportEmail() *string {
	if e == nil {
		return nil
	}
	return e.SupportEmail
}

func (e *Endpoint) GetUID() *string {
	if e == nil {
		return nil
	}
	return e.UID
}

func (e *Endpoint) GetUpdatedAt() *string {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}

func (e *Endpoint) GetURL() *string {
	if e == nil {
		return nil
	}
	return e.URL
}
