// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type EventDeliveryStatus string

const (
	EventDeliveryStatusScheduled  EventDeliveryStatus = "Scheduled"
	EventDeliveryStatusProcessing EventDeliveryStatus = "Processing"
	EventDeliveryStatusDiscarded  EventDeliveryStatus = "Discarded"
	EventDeliveryStatusFailure    EventDeliveryStatus = "Failure"
	EventDeliveryStatusSuccess    EventDeliveryStatus = "Success"
	EventDeliveryStatusRetry      EventDeliveryStatus = "Retry"
)

func (e EventDeliveryStatus) ToPointer() *EventDeliveryStatus {
	return &e
}
func (e *EventDeliveryStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Scheduled":
		fallthrough
	case "Processing":
		fallthrough
	case "Discarded":
		fallthrough
	case "Failure":
		fallthrough
	case "Success":
		fallthrough
	case "Retry":
		*e = EventDeliveryStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EventDeliveryStatus: %v", v)
	}
}
