// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type EventTypeResponse struct {
	Category     *string `json:"category,omitempty"`
	DeprecatedAt *string `json:"deprecated_at,omitempty"`
	Description  *string `json:"description,omitempty"`
	JSONSchema   []int64 `json:"json_schema,omitempty"`
	Name         *string `json:"name,omitempty"`
	UID          *string `json:"uid,omitempty"`
}

func (o *EventTypeResponse) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *EventTypeResponse) GetDeprecatedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeprecatedAt
}

func (o *EventTypeResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *EventTypeResponse) GetJSONSchema() []int64 {
	if o == nil {
		return nil
	}
	return o.JSONSchema
}

func (o *EventTypeResponse) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *EventTypeResponse) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}
