// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type ExpireSecret struct {
	// Amount of time to wait before expiring the old endpoint secret.
	// If AdvancedSignatures is turned on for the project, signatures for both secrets will be generated up until
	// the old signature is expired.
	Expiration *int64 `json:"expiration,omitempty"`
	// New Endpoint secret value.
	Secret *string `json:"secret,omitempty"`
}

func (o *ExpireSecret) GetExpiration() *int64 {
	if o == nil {
		return nil
	}
	return o.Expiration
}

func (o *ExpireSecret) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}
