// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type ExpireSecretRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Endpoint ID
	EndpointID string `pathParam:"style=simple,explode=false,name=endpointID"`
	// Expire Secret Body Parameters
	ExpireSecret ExpireSecret `request:"mediaType=application/json"`
}

func (o *ExpireSecretRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *ExpireSecretRequest) GetEndpointID() string {
	if o == nil {
		return ""
	}
	return o.EndpointID
}

func (o *ExpireSecretRequest) GetExpireSecret() ExpireSecret {
	if o == nil {
		return ExpireSecret{}
	}
	return o.ExpireSecret
}

// ExpireSecretNotFoundError - Not Found
type ExpireSecretNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ExpireSecretNotFoundError{}

func (e *ExpireSecretNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ExpireSecretUnauthorizedError - Unauthorized
type ExpireSecretUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ExpireSecretUnauthorizedError{}

func (e *ExpireSecretUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ExpireSecretBadRequestError - Bad Request
type ExpireSecretBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ExpireSecretBadRequestError{}

func (e *ExpireSecretBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ExpireSecretResponseBody - OK
type ExpireSecretResponseBody struct {
	Message *string           `json:"message,omitempty"`
	Status  *bool             `json:"status,omitempty"`
	Data    *EndpointResponse `json:"data,omitempty"`
}

func (o *ExpireSecretResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *ExpireSecretResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ExpireSecretResponseBody) GetData() *EndpointResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type ExpireSecretResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *ExpireSecretResponseBody
}

func (o *ExpireSecretResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ExpireSecretResponse) GetObject() *ExpireSecretResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
