// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

// FanoutEventData - Data is an arbitrary JSON value that gets sent as the body of the
// webhook to the endpoints
type FanoutEventData struct {
}

type FanoutEvent struct {
	// Specifies custom headers you want convoy to add when the event is dispatched to your endpoint
	CustomHeaders map[string]string `json:"custom_headers,omitempty"`
	// Data is an arbitrary JSON value that gets sent as the body of the
	// webhook to the endpoints
	Data *FanoutEventData `json:"data,omitempty"`
	// Event Type is used for filtering and debugging e.g invoice.paid
	EventType *string `json:"event_type,omitempty"`
	// Specify a key for event deduplication
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Used for fanout, sends this event to all endpoints with this OwnerID.
	OwnerID *string `json:"owner_id,omitempty"`
}

func (f *FanoutEvent) GetCustomHeaders() map[string]string {
	if f == nil {
		return nil
	}
	return f.CustomHeaders
}

func (f *FanoutEvent) GetData() *FanoutEventData {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FanoutEvent) GetEventType() *string {
	if f == nil {
		return nil
	}
	return f.EventType
}

func (f *FanoutEvent) GetIdempotencyKey() *string {
	if f == nil {
		return nil
	}
	return f.IdempotencyKey
}

func (f *FanoutEvent) GetOwnerID() *string {
	if f == nil {
		return nil
	}
	return f.OwnerID
}
