// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type FilterSchema struct {
	Body   any `json:"body,omitempty"`
	Header any `json:"header,omitempty"`
}

func (f *FilterSchema) GetBody() any {
	if f == nil {
		return nil
	}
	return f.Body
}

func (f *FilterSchema) GetHeader() any {
	if f == nil {
		return nil
	}
	return f.Header
}
