// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type FilterSchema struct {
	Body   any `json:"body,omitempty"`
	Header any `json:"header,omitempty"`
}

func (o *FilterSchema) GetBody() any {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *FilterSchema) GetHeader() any {
	if o == nil {
		return nil
	}
	return o.Header
}
