// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type FilterConfiguration struct {
	// List of event types that the subscription should match
	EventTypes []string `json:"event_types,omitempty"`
	// Body & Header filters
	Filter *Fs `json:"filter,omitempty"`
}

func (o *FilterConfiguration) GetEventTypes() []string {
	if o == nil {
		return nil
	}
	return o.EventTypes
}

func (o *FilterConfiguration) GetFilter() *Fs {
	if o == nil {
		return nil
	}
	return o.Filter
}
