// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type ForceResendEventDeliveriesRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// event delivery ids
	IDs IDs `request:"mediaType=application/json"`
}

func (f *ForceResendEventDeliveriesRequest) GetProjectID() string {
	if f == nil {
		return ""
	}
	return f.ProjectID
}

func (f *ForceResendEventDeliveriesRequest) GetIDs() IDs {
	if f == nil {
		return IDs{}
	}
	return f.IDs
}

// ForceResendEventDeliveriesNotFoundError - Not Found
type ForceResendEventDeliveriesNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ForceResendEventDeliveriesNotFoundError{}

func (e *ForceResendEventDeliveriesNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ForceResendEventDeliveriesUnauthorizedError - Unauthorized
type ForceResendEventDeliveriesUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ForceResendEventDeliveriesUnauthorizedError{}

func (e *ForceResendEventDeliveriesUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ForceResendEventDeliveriesBadRequestError - Bad Request
type ForceResendEventDeliveriesBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ForceResendEventDeliveriesBadRequestError{}

func (e *ForceResendEventDeliveriesBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ForceResendEventDeliveriesResponseBody - OK
type ForceResendEventDeliveriesResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *Object `json:"data,omitempty"`
}

func (f *ForceResendEventDeliveriesResponseBody) GetMessage() *string {
	if f == nil {
		return nil
	}
	return f.Message
}

func (f *ForceResendEventDeliveriesResponseBody) GetStatus() *bool {
	if f == nil {
		return nil
	}
	return f.Status
}

func (f *ForceResendEventDeliveriesResponseBody) GetData() *Object {
	if f == nil {
		return nil
	}
	return f.Data
}

type ForceResendEventDeliveriesResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *ForceResendEventDeliveriesResponseBody
}

func (f *ForceResendEventDeliveriesResponse) GetHTTPMeta() HTTPMetadata {
	if f == nil {
		return HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *ForceResendEventDeliveriesResponse) GetObject() *ForceResendEventDeliveriesResponseBody {
	if f == nil {
		return nil
	}
	return f.Object
}
