// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type Fs struct {
	Body    map[string]any `json:"body,omitempty"`
	Headers map[string]any `json:"headers,omitempty"`
}

func (f *Fs) GetBody() map[string]any {
	if f == nil {
		return nil
	}
	return f.Body
}

func (f *Fs) GetHeaders() map[string]any {
	if f == nil {
		return nil
	}
	return f.Headers
}
