// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type FunctionResponse struct {
	Log     []string `json:"log,omitempty"`
	Payload any      `json:"payload,omitempty"`
}

func (f *FunctionResponse) GetLog() []string {
	if f == nil {
		return nil
	}
	return f.Log
}

func (f *FunctionResponse) GetPayload() any {
	if f == nil {
		return nil
	}
	return f.Payload
}
