// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0bbaea0744b1

package convoy

type FunctionRequest struct {
	Function *string        `json:"function,omitempty"`
	Payload  map[string]any `json:"payload,omitempty"`
	Type     *string        `json:"type,omitempty"`
}

func (f *FunctionRequest) GetFunction() *string {
	if f == nil {
		return nil
	}
	return f.Function
}

func (f *FunctionRequest) GetPayload() map[string]any {
	if f == nil {
		return nil
	}
	return f.Payload
}

func (f *FunctionRequest) GetType() *string {
	if f == nil {
		return nil
	}
	return f.Type
}
