// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetEventDeliveryRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// event delivery id
	EventDeliveryID string `pathParam:"style=simple,explode=false,name=eventDeliveryID"`
}

func (o *GetEventDeliveryRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *GetEventDeliveryRequest) GetEventDeliveryID() string {
	if o == nil {
		return ""
	}
	return o.EventDeliveryID
}

// GetEventDeliveryNotFoundError - Not Found
type GetEventDeliveryNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventDeliveryNotFoundError{}

func (e *GetEventDeliveryNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventDeliveryUnauthorizedError - Unauthorized
type GetEventDeliveryUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventDeliveryUnauthorizedError{}

func (e *GetEventDeliveryUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventDeliveryBadRequestError - Bad Request
type GetEventDeliveryBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventDeliveryBadRequestError{}

func (e *GetEventDeliveryBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventDeliveryResponseBody - OK
type GetEventDeliveryResponseBody struct {
	Message *string                `json:"message,omitempty"`
	Status  *bool                  `json:"status,omitempty"`
	Data    *EventDeliveryResponse `json:"data,omitempty"`
}

func (o *GetEventDeliveryResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetEventDeliveryResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetEventDeliveryResponseBody) GetData() *EventDeliveryResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetEventDeliveryResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetEventDeliveryResponseBody
}

func (o *GetEventDeliveryResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetEventDeliveryResponse) GetObject() *GetEventDeliveryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
