// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetEventTypesRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
}

func (g *GetEventTypesRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

// GetEventTypesNotFoundError - Not Found
type GetEventTypesNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventTypesNotFoundError{}

func (e *GetEventTypesNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventTypesUnauthorizedError - Unauthorized
type GetEventTypesUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventTypesUnauthorizedError{}

func (e *GetEventTypesUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventTypesBadRequestError - Bad Request
type GetEventTypesBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventTypesBadRequestError{}

func (e *GetEventTypesBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventTypesResponseBody - OK
type GetEventTypesResponseBody struct {
	Message *string             `json:"message,omitempty"`
	Status  *bool               `json:"status,omitempty"`
	Data    []EventTypeResponse `json:"data,omitempty"`
}

func (g *GetEventTypesResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetEventTypesResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetEventTypesResponseBody) GetData() []EventTypeResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetEventTypesResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetEventTypesResponseBody
}

func (g *GetEventTypesResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEventTypesResponse) GetObject() *GetEventTypesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
