// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type GetEventsPagedDirection string

const (
	GetEventsPagedDirectionNext GetEventsPagedDirection = "next"
	GetEventsPagedDirectionPrev GetEventsPagedDirection = "prev"
)

func (e GetEventsPagedDirection) ToPointer() *GetEventsPagedDirection {
	return &e
}
func (e *GetEventsPagedDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "next":
		fallthrough
	case "prev":
		*e = GetEventsPagedDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetEventsPagedDirection: %v", v)
	}
}

type GetEventsPagedRequest struct {
	// Project ID
	ProjectID string                   `pathParam:"style=simple,explode=false,name=projectID"`
	Direction *GetEventsPagedDirection `queryParam:"style=form,explode=true,name=direction"`
	// The end date
	EndDate *string `queryParam:"style=form,explode=true,name=endDate"`
	// A list of endpoint ids to filter by
	EndpointID []string `queryParam:"style=form,explode=true,name=endpointId"`
	// IdempotencyKey to filter by
	IdempotencyKey *string `queryParam:"style=form,explode=true,name=idempotencyKey"`
	// A pagination cursor to fetch the next page of a list
	NextPageCursor *string `queryParam:"style=form,explode=true,name=next_page_cursor"`
	// The number of items to return per page
	PerPage *int64 `queryParam:"style=form,explode=true,name=perPage"`
	// A pagination cursor to fetch the previous page of a list
	PrevPageCursor *string `queryParam:"style=form,explode=true,name=prev_page_cursor"`
	// Any arbitrary value to filter the events payload
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Sort order, values are `ASC` or `DESC`, defaults to `DESC`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// A list of Source IDs to filter the events by.
	SourceID []string `queryParam:"style=form,explode=true,name=sourceId"`
	// The start date
	StartDate *string `queryParam:"style=form,explode=true,name=startDate"`
}

func (g *GetEventsPagedRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetEventsPagedRequest) GetDirection() *GetEventsPagedDirection {
	if g == nil {
		return nil
	}
	return g.Direction
}

func (g *GetEventsPagedRequest) GetEndDate() *string {
	if g == nil {
		return nil
	}
	return g.EndDate
}

func (g *GetEventsPagedRequest) GetEndpointID() []string {
	if g == nil {
		return nil
	}
	return g.EndpointID
}

func (g *GetEventsPagedRequest) GetIdempotencyKey() *string {
	if g == nil {
		return nil
	}
	return g.IdempotencyKey
}

func (g *GetEventsPagedRequest) GetNextPageCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextPageCursor
}

func (g *GetEventsPagedRequest) GetPerPage() *int64 {
	if g == nil {
		return nil
	}
	return g.PerPage
}

func (g *GetEventsPagedRequest) GetPrevPageCursor() *string {
	if g == nil {
		return nil
	}
	return g.PrevPageCursor
}

func (g *GetEventsPagedRequest) GetQuery() *string {
	if g == nil {
		return nil
	}
	return g.Query
}

func (g *GetEventsPagedRequest) GetSort() *string {
	if g == nil {
		return nil
	}
	return g.Sort
}

func (g *GetEventsPagedRequest) GetSourceID() []string {
	if g == nil {
		return nil
	}
	return g.SourceID
}

func (g *GetEventsPagedRequest) GetStartDate() *string {
	if g == nil {
		return nil
	}
	return g.StartDate
}

// GetEventsPagedNotFoundError - Not Found
type GetEventsPagedNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventsPagedNotFoundError{}

func (e *GetEventsPagedNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventsPagedUnauthorizedError - Unauthorized
type GetEventsPagedUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventsPagedUnauthorizedError{}

func (e *GetEventsPagedUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventsPagedBadRequestError - Bad Request
type GetEventsPagedBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventsPagedBadRequestError{}

func (e *GetEventsPagedBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetEventsPagedData struct {
	Content    []EventResponse `json:"content,omitempty"`
	Pagination *PaginationData `json:"pagination,omitempty"`
}

func (g *GetEventsPagedData) GetContent() []EventResponse {
	if g == nil {
		return nil
	}
	return g.Content
}

func (g *GetEventsPagedData) GetPagination() *PaginationData {
	if g == nil {
		return nil
	}
	return g.Pagination
}

// GetEventsPagedResponseBody - OK
type GetEventsPagedResponseBody struct {
	Message *string             `json:"message,omitempty"`
	Status  *bool               `json:"status,omitempty"`
	Data    *GetEventsPagedData `json:"data,omitempty"`
}

func (g *GetEventsPagedResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetEventsPagedResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetEventsPagedResponseBody) GetData() *GetEventsPagedData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetEventsPagedResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetEventsPagedResponseBody
}

func (g *GetEventsPagedResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEventsPagedResponse) GetObject() *GetEventsPagedResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
