// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetEndpointEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// event id
	EventID string `pathParam:"style=simple,explode=false,name=eventID"`
}

func (o *GetEndpointEventRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *GetEndpointEventRequest) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

// GetEndpointEventNotFoundError - Not Found
type GetEndpointEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEndpointEventNotFoundError{}

func (e *GetEndpointEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEndpointEventUnauthorizedError - Unauthorized
type GetEndpointEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEndpointEventUnauthorizedError{}

func (e *GetEndpointEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEndpointEventBadRequestError - Bad Request
type GetEndpointEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEndpointEventBadRequestError{}

func (e *GetEndpointEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEndpointEventResponseBody - OK
type GetEndpointEventResponseBody struct {
	Message *string        `json:"message,omitempty"`
	Status  *bool          `json:"status,omitempty"`
	Data    *EventResponse `json:"data,omitempty"`
}

func (o *GetEndpointEventResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetEndpointEventResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetEndpointEventResponseBody) GetData() *EventResponse {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetEndpointEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetEndpointEventResponseBody
}

func (o *GetEndpointEventResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetEndpointEventResponse) GetObject() *GetEndpointEventResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
