// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type GetEventDeliveriesPagedDirection string

const (
	GetEventDeliveriesPagedDirectionNext GetEventDeliveriesPagedDirection = "next"
	GetEventDeliveriesPagedDirectionPrev GetEventDeliveriesPagedDirection = "prev"
)

func (e GetEventDeliveriesPagedDirection) ToPointer() *GetEventDeliveriesPagedDirection {
	return &e
}
func (e *GetEventDeliveriesPagedDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "next":
		fallthrough
	case "prev":
		*e = GetEventDeliveriesPagedDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetEventDeliveriesPagedDirection: %v", v)
	}
}

type GetEventDeliveriesPagedRequest struct {
	// Project ID
	ProjectID string                            `pathParam:"style=simple,explode=false,name=projectID"`
	Direction *GetEventDeliveriesPagedDirection `queryParam:"style=form,explode=true,name=direction"`
	// The end date
	EndDate *string `queryParam:"style=form,explode=true,name=endDate"`
	// A list of endpoint IDs to filter by
	EndpointID []string `queryParam:"style=form,explode=true,name=endpointId"`
	// Event ID to filter by
	EventID *string `queryParam:"style=form,explode=true,name=eventId"`
	// EventType to filter by
	EventType *string `queryParam:"style=form,explode=true,name=event_type"`
	// IdempotencyKey to filter by
	IdempotencyKey *string `queryParam:"style=form,explode=true,name=idempotencyKey"`
	// A pagination cursor to fetch the next page of a list
	NextPageCursor *string `queryParam:"style=form,explode=true,name=next_page_cursor"`
	// The number of items to return per page
	PerPage *int64 `queryParam:"style=form,explode=true,name=perPage"`
	// A pagination cursor to fetch the previous page of a list
	PrevPageCursor *string `queryParam:"style=form,explode=true,name=prev_page_cursor"`
	// Sort order, values are `ASC` or `DESC`, defaults to `DESC`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// The start date
	StartDate *string `queryParam:"style=form,explode=true,name=startDate"`
	// A list of event delivery statuses to filter by
	Status []string `queryParam:"style=form,explode=true,name=status"`
	// SubscriptionID to filter by
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscriptionId"`
}

func (g *GetEventDeliveriesPagedRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetEventDeliveriesPagedRequest) GetDirection() *GetEventDeliveriesPagedDirection {
	if g == nil {
		return nil
	}
	return g.Direction
}

func (g *GetEventDeliveriesPagedRequest) GetEndDate() *string {
	if g == nil {
		return nil
	}
	return g.EndDate
}

func (g *GetEventDeliveriesPagedRequest) GetEndpointID() []string {
	if g == nil {
		return nil
	}
	return g.EndpointID
}

func (g *GetEventDeliveriesPagedRequest) GetEventID() *string {
	if g == nil {
		return nil
	}
	return g.EventID
}

func (g *GetEventDeliveriesPagedRequest) GetEventType() *string {
	if g == nil {
		return nil
	}
	return g.EventType
}

func (g *GetEventDeliveriesPagedRequest) GetIdempotencyKey() *string {
	if g == nil {
		return nil
	}
	return g.IdempotencyKey
}

func (g *GetEventDeliveriesPagedRequest) GetNextPageCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextPageCursor
}

func (g *GetEventDeliveriesPagedRequest) GetPerPage() *int64 {
	if g == nil {
		return nil
	}
	return g.PerPage
}

func (g *GetEventDeliveriesPagedRequest) GetPrevPageCursor() *string {
	if g == nil {
		return nil
	}
	return g.PrevPageCursor
}

func (g *GetEventDeliveriesPagedRequest) GetSort() *string {
	if g == nil {
		return nil
	}
	return g.Sort
}

func (g *GetEventDeliveriesPagedRequest) GetStartDate() *string {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetEventDeliveriesPagedRequest) GetStatus() []string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetEventDeliveriesPagedRequest) GetSubscriptionID() *string {
	if g == nil {
		return nil
	}
	return g.SubscriptionID
}

// GetEventDeliveriesPagedNotFoundError - Not Found
type GetEventDeliveriesPagedNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventDeliveriesPagedNotFoundError{}

func (e *GetEventDeliveriesPagedNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventDeliveriesPagedUnauthorizedError - Unauthorized
type GetEventDeliveriesPagedUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventDeliveriesPagedUnauthorizedError{}

func (e *GetEventDeliveriesPagedUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetEventDeliveriesPagedBadRequestError - Bad Request
type GetEventDeliveriesPagedBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetEventDeliveriesPagedBadRequestError{}

func (e *GetEventDeliveriesPagedBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetEventDeliveriesPagedData struct {
	Content    []EventDeliveryResponse `json:"content,omitempty"`
	Pagination *PaginationData         `json:"pagination,omitempty"`
}

func (g *GetEventDeliveriesPagedData) GetContent() []EventDeliveryResponse {
	if g == nil {
		return nil
	}
	return g.Content
}

func (g *GetEventDeliveriesPagedData) GetPagination() *PaginationData {
	if g == nil {
		return nil
	}
	return g.Pagination
}

// GetEventDeliveriesPagedResponseBody - OK
type GetEventDeliveriesPagedResponseBody struct {
	Message *string                      `json:"message,omitempty"`
	Status  *bool                        `json:"status,omitempty"`
	Data    *GetEventDeliveriesPagedData `json:"data,omitempty"`
}

func (g *GetEventDeliveriesPagedResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetEventDeliveriesPagedResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetEventDeliveriesPagedResponseBody) GetData() *GetEventDeliveriesPagedData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetEventDeliveriesPagedResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetEventDeliveriesPagedResponseBody
}

func (g *GetEventDeliveriesPagedResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEventDeliveriesPagedResponse) GetObject() *GetEventDeliveriesPagedResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
