// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetFiltersRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
}

func (g *GetFiltersRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetFiltersRequest) GetSubscriptionID() string {
	if g == nil {
		return ""
	}
	return g.SubscriptionID
}

// GetFiltersNotFoundError - Not Found
type GetFiltersNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetFiltersNotFoundError{}

func (e *GetFiltersNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetFiltersUnauthorizedError - Unauthorized
type GetFiltersUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetFiltersUnauthorizedError{}

func (e *GetFiltersUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetFiltersBadRequestError - Bad Request
type GetFiltersBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetFiltersBadRequestError{}

func (e *GetFiltersBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetFiltersResponseBody - OK
type GetFiltersResponseBody struct {
	Message *string          `json:"message,omitempty"`
	Status  *bool            `json:"status,omitempty"`
	Data    []FilterResponse `json:"data,omitempty"`
}

func (g *GetFiltersResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetFiltersResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetFiltersResponseBody) GetData() []FilterResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetFiltersResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetFiltersResponseBody
}

func (g *GetFiltersResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetFiltersResponse) GetObject() *GetFiltersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
