// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type GetMetaEventsPagedDirection string

const (
	GetMetaEventsPagedDirectionNext GetMetaEventsPagedDirection = "next"
	GetMetaEventsPagedDirectionPrev GetMetaEventsPagedDirection = "prev"
)

func (e GetMetaEventsPagedDirection) ToPointer() *GetMetaEventsPagedDirection {
	return &e
}
func (e *GetMetaEventsPagedDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "next":
		fallthrough
	case "prev":
		*e = GetMetaEventsPagedDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMetaEventsPagedDirection: %v", v)
	}
}

type GetMetaEventsPagedRequest struct {
	// Project ID
	ProjectID string                       `pathParam:"style=simple,explode=false,name=projectID"`
	Direction *GetMetaEventsPagedDirection `queryParam:"style=form,explode=true,name=direction"`
	// The end date
	EndDate *string `queryParam:"style=form,explode=true,name=endDate"`
	// A pagination cursor to fetch the next page of a list
	NextPageCursor *string `queryParam:"style=form,explode=true,name=next_page_cursor"`
	// The number of items to return per page
	PerPage *int64 `queryParam:"style=form,explode=true,name=perPage"`
	// A pagination cursor to fetch the previous page of a list
	PrevPageCursor *string `queryParam:"style=form,explode=true,name=prev_page_cursor"`
	// Sort order, values are `ASC` or `DESC`, defaults to `DESC`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// The start date
	StartDate *string `queryParam:"style=form,explode=true,name=startDate"`
}

func (g *GetMetaEventsPagedRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetMetaEventsPagedRequest) GetDirection() *GetMetaEventsPagedDirection {
	if g == nil {
		return nil
	}
	return g.Direction
}

func (g *GetMetaEventsPagedRequest) GetEndDate() *string {
	if g == nil {
		return nil
	}
	return g.EndDate
}

func (g *GetMetaEventsPagedRequest) GetNextPageCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextPageCursor
}

func (g *GetMetaEventsPagedRequest) GetPerPage() *int64 {
	if g == nil {
		return nil
	}
	return g.PerPage
}

func (g *GetMetaEventsPagedRequest) GetPrevPageCursor() *string {
	if g == nil {
		return nil
	}
	return g.PrevPageCursor
}

func (g *GetMetaEventsPagedRequest) GetSort() *string {
	if g == nil {
		return nil
	}
	return g.Sort
}

func (g *GetMetaEventsPagedRequest) GetStartDate() *string {
	if g == nil {
		return nil
	}
	return g.StartDate
}

// GetMetaEventsPagedNotFoundError - Not Found
type GetMetaEventsPagedNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetMetaEventsPagedNotFoundError{}

func (e *GetMetaEventsPagedNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetMetaEventsPagedUnauthorizedError - Unauthorized
type GetMetaEventsPagedUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetMetaEventsPagedUnauthorizedError{}

func (e *GetMetaEventsPagedUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetMetaEventsPagedBadRequestError - Bad Request
type GetMetaEventsPagedBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetMetaEventsPagedBadRequestError{}

func (e *GetMetaEventsPagedBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetMetaEventsPagedData struct {
	Content    []MetaEventResponse `json:"content,omitempty"`
	Pagination *PaginationData     `json:"pagination,omitempty"`
}

func (g *GetMetaEventsPagedData) GetContent() []MetaEventResponse {
	if g == nil {
		return nil
	}
	return g.Content
}

func (g *GetMetaEventsPagedData) GetPagination() *PaginationData {
	if g == nil {
		return nil
	}
	return g.Pagination
}

// GetMetaEventsPagedResponseBody - OK
type GetMetaEventsPagedResponseBody struct {
	Message *string                 `json:"message,omitempty"`
	Status  *bool                   `json:"status,omitempty"`
	Data    *GetMetaEventsPagedData `json:"data,omitempty"`
}

func (g *GetMetaEventsPagedResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetMetaEventsPagedResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetMetaEventsPagedResponseBody) GetData() *GetMetaEventsPagedData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetMetaEventsPagedResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetMetaEventsPagedResponseBody
}

func (g *GetMetaEventsPagedResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMetaEventsPagedResponse) GetObject() *GetMetaEventsPagedResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
