// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetMetaEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// meta event id
	MetaEventID string `pathParam:"style=simple,explode=false,name=metaEventID"`
}

func (g *GetMetaEventRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetMetaEventRequest) GetMetaEventID() string {
	if g == nil {
		return ""
	}
	return g.MetaEventID
}

// GetMetaEventNotFoundError - Not Found
type GetMetaEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetMetaEventNotFoundError{}

func (e *GetMetaEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetMetaEventUnauthorizedError - Unauthorized
type GetMetaEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetMetaEventUnauthorizedError{}

func (e *GetMetaEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetMetaEventBadRequestError - Bad Request
type GetMetaEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetMetaEventBadRequestError{}

func (e *GetMetaEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetMetaEventResponseBody - OK
type GetMetaEventResponseBody struct {
	Message *string            `json:"message,omitempty"`
	Status  *bool              `json:"status,omitempty"`
	Data    *MetaEventResponse `json:"data,omitempty"`
}

func (g *GetMetaEventResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetMetaEventResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetMetaEventResponseBody) GetData() *MetaEventResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetMetaEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetMetaEventResponseBody
}

func (g *GetMetaEventResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMetaEventResponse) GetObject() *GetMetaEventResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
