// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetPortalLinkRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// portal link id
	PortalLinkID string `pathParam:"style=simple,explode=false,name=portalLinkID"`
}

func (g *GetPortalLinkRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetPortalLinkRequest) GetPortalLinkID() string {
	if g == nil {
		return ""
	}
	return g.PortalLinkID
}

// GetPortalLinkNotFoundError - Not Found
type GetPortalLinkNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetPortalLinkNotFoundError{}

func (e *GetPortalLinkNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetPortalLinkUnauthorizedError - Unauthorized
type GetPortalLinkUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetPortalLinkUnauthorizedError{}

func (e *GetPortalLinkUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetPortalLinkBadRequestError - Bad Request
type GetPortalLinkBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetPortalLinkBadRequestError{}

func (e *GetPortalLinkBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetPortalLinkResponseBody - OK
type GetPortalLinkResponseBody struct {
	Message *string             `json:"message,omitempty"`
	Status  *bool               `json:"status,omitempty"`
	Data    *PortalLinkResponse `json:"data,omitempty"`
}

func (g *GetPortalLinkResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetPortalLinkResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetPortalLinkResponseBody) GetData() *PortalLinkResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetPortalLinkResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetPortalLinkResponseBody
}

func (g *GetPortalLinkResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPortalLinkResponse) GetObject() *GetPortalLinkResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
