// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetSubscriptionRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// subscription id
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
}

func (g *GetSubscriptionRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetSubscriptionRequest) GetSubscriptionID() string {
	if g == nil {
		return ""
	}
	return g.SubscriptionID
}

// GetSubscriptionNotFoundError - Not Found
type GetSubscriptionNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetSubscriptionNotFoundError{}

func (e *GetSubscriptionNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSubscriptionUnauthorizedError - Unauthorized
type GetSubscriptionUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetSubscriptionUnauthorizedError{}

func (e *GetSubscriptionUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSubscriptionBadRequestError - Bad Request
type GetSubscriptionBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetSubscriptionBadRequestError{}

func (e *GetSubscriptionBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSubscriptionResponseBody - OK
type GetSubscriptionResponseBody struct {
	Message *string               `json:"message,omitempty"`
	Status  *bool                 `json:"status,omitempty"`
	Data    *SubscriptionResponse `json:"data,omitempty"`
}

func (g *GetSubscriptionResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSubscriptionResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetSubscriptionResponseBody) GetData() *SubscriptionResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetSubscriptionResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetSubscriptionResponseBody
}

func (g *GetSubscriptionResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubscriptionResponse) GetObject() *GetSubscriptionResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
