// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type GetSourceRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Source ID
	SourceID string `pathParam:"style=simple,explode=false,name=sourceID"`
}

func (g *GetSourceRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetSourceRequest) GetSourceID() string {
	if g == nil {
		return ""
	}
	return g.SourceID
}

// GetSourceNotFoundError - Not Found
type GetSourceNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetSourceNotFoundError{}

func (e *GetSourceNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSourceUnauthorizedError - Unauthorized
type GetSourceUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetSourceUnauthorizedError{}

func (e *GetSourceUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSourceBadRequestError - Bad Request
type GetSourceBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &GetSourceBadRequestError{}

func (e *GetSourceBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSourceResponseBody - OK
type GetSourceResponseBody struct {
	Message *string         `json:"message,omitempty"`
	Status  *bool           `json:"status,omitempty"`
	Data    *SourceResponse `json:"data,omitempty"`
}

func (g *GetSourceResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSourceResponseBody) GetStatus() *bool {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetSourceResponseBody) GetData() *SourceResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetSourceResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetSourceResponseBody
}

func (g *GetSourceResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSourceResponse) GetObject() *GetSourceResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
