// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type GooglePubSubConfig struct {
	ProjectID      *string `json:"project_id,omitempty"`
	ServiceAccount []int64 `json:"service_account,omitempty"`
	SubscriptionID *string `json:"subscription_id,omitempty"`
}

func (o *GooglePubSubConfig) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *GooglePubSubConfig) GetServiceAccount() []int64 {
	if o == nil {
		return nil
	}
	return o.ServiceAccount
}

func (o *GooglePubSubConfig) GetSubscriptionID() *string {
	if o == nil {
		return nil
	}
	return o.SubscriptionID
}
