// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type GooglePubSubConfig struct {
	ProjectID      *string `json:"project_id,omitempty"`
	ServiceAccount []int64 `json:"service_account,omitempty"`
	SubscriptionID *string `json:"subscription_id,omitempty"`
}

func (g *GooglePubSubConfig) GetProjectID() *string {
	if g == nil {
		return nil
	}
	return g.ProjectID
}

func (g *GooglePubSubConfig) GetServiceAccount() []int64 {
	if g == nil {
		return nil
	}
	return g.ServiceAccount
}

func (g *GooglePubSubConfig) GetSubscriptionID() *string {
	if g == nil {
		return nil
	}
	return g.SubscriptionID
}
