// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type HMac struct {
	Encoding EncodingType `json:"encoding"`
	Hash     string       `json:"hash"`
	Header   string       `json:"header"`
	Secret   string       `json:"secret"`
}

func (o *HMac) GetEncoding() EncodingType {
	if o == nil {
		return EncodingType("")
	}
	return o.Encoding
}

func (o *HMac) GetHash() string {
	if o == nil {
		return ""
	}
	return o.Hash
}

func (o *HMac) GetHeader() string {
	if o == nil {
		return ""
	}
	return o.Header
}

func (o *HMac) GetSecret() string {
	if o == nil {
		return ""
	}
	return o.Secret
}
