// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type IDs struct {
	// A list of event delivery IDs to forcefully resend.
	Ids []string `json:"ids,omitempty"`
}

func (o *IDs) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}
