// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type ImportOpenAPISpec struct {
	Spec *string `json:"spec,omitempty"`
}

func (i *ImportOpenAPISpec) GetSpec() *string {
	if i == nil {
		return nil
	}
	return i.Spec
}
