// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type ImportOpenAPISpec struct {
	Spec *string `json:"spec,omitempty"`
}

func (o *ImportOpenAPISpec) GetSpec() *string {
	if o == nil {
		return nil
	}
	return o.Spec
}
