// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type KafkaAuth struct {
	Hash     *string `json:"hash,omitempty"`
	Password *string `json:"password,omitempty"`
	TLS      *bool   `json:"tls,omitempty"`
	Type     *string `json:"type,omitempty"`
	Username *string `json:"username,omitempty"`
}

func (o *KafkaAuth) GetHash() *string {
	if o == nil {
		return nil
	}
	return o.Hash
}

func (o *KafkaAuth) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *KafkaAuth) GetTLS() *bool {
	if o == nil {
		return nil
	}
	return o.TLS
}

func (o *KafkaAuth) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *KafkaAuth) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}
