// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type KafkaPubSubConfig struct {
	Auth            *KafkaAuth `json:"auth,omitempty"`
	Brokers         []string   `json:"brokers,omitempty"`
	ConsumerGroupID *string    `json:"consumer_group_id,omitempty"`
	TopicName       *string    `json:"topic_name,omitempty"`
}

func (o *KafkaPubSubConfig) GetAuth() *KafkaAuth {
	if o == nil {
		return nil
	}
	return o.Auth
}

func (o *KafkaPubSubConfig) GetBrokers() []string {
	if o == nil {
		return nil
	}
	return o.Brokers
}

func (o *KafkaPubSubConfig) GetConsumerGroupID() *string {
	if o == nil {
		return nil
	}
	return o.ConsumerGroupID
}

func (o *KafkaPubSubConfig) GetTopicName() *string {
	if o == nil {
		return nil
	}
	return o.TopicName
}
