// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type LoadPortalLinksPagedDirection string

const (
	LoadPortalLinksPagedDirectionNext LoadPortalLinksPagedDirection = "next"
	LoadPortalLinksPagedDirectionPrev LoadPortalLinksPagedDirection = "prev"
)

func (e LoadPortalLinksPagedDirection) ToPointer() *LoadPortalLinksPagedDirection {
	return &e
}
func (e *LoadPortalLinksPagedDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "next":
		fallthrough
	case "prev":
		*e = LoadPortalLinksPagedDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LoadPortalLinksPagedDirection: %v", v)
	}
}

type LoadPortalLinksPagedRequest struct {
	// Project ID
	ProjectID string                         `pathParam:"style=simple,explode=false,name=projectID"`
	Direction *LoadPortalLinksPagedDirection `queryParam:"style=form,explode=true,name=direction"`
	// A pagination cursor to fetch the next page of a list
	NextPageCursor *string `queryParam:"style=form,explode=true,name=next_page_cursor"`
	// The owner ID of the endpoint
	OwnerID *string `queryParam:"style=form,explode=true,name=ownerId"`
	// The number of items to return per page
	PerPage *int64 `queryParam:"style=form,explode=true,name=perPage"`
	// A pagination cursor to fetch the previous page of a list
	PrevPageCursor *string `queryParam:"style=form,explode=true,name=prev_page_cursor"`
	// The name of the endpoint
	Q *string `queryParam:"style=form,explode=true,name=q"`
	// Sort order, values are `ASC` or `DESC`, defaults to `DESC`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
}

func (l *LoadPortalLinksPagedRequest) GetProjectID() string {
	if l == nil {
		return ""
	}
	return l.ProjectID
}

func (l *LoadPortalLinksPagedRequest) GetDirection() *LoadPortalLinksPagedDirection {
	if l == nil {
		return nil
	}
	return l.Direction
}

func (l *LoadPortalLinksPagedRequest) GetNextPageCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextPageCursor
}

func (l *LoadPortalLinksPagedRequest) GetOwnerID() *string {
	if l == nil {
		return nil
	}
	return l.OwnerID
}

func (l *LoadPortalLinksPagedRequest) GetPerPage() *int64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *LoadPortalLinksPagedRequest) GetPrevPageCursor() *string {
	if l == nil {
		return nil
	}
	return l.PrevPageCursor
}

func (l *LoadPortalLinksPagedRequest) GetQ() *string {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *LoadPortalLinksPagedRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

// LoadPortalLinksPagedNotFoundError - Not Found
type LoadPortalLinksPagedNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &LoadPortalLinksPagedNotFoundError{}

func (e *LoadPortalLinksPagedNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// LoadPortalLinksPagedUnauthorizedError - Unauthorized
type LoadPortalLinksPagedUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &LoadPortalLinksPagedUnauthorizedError{}

func (e *LoadPortalLinksPagedUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// LoadPortalLinksPagedBadRequestError - Bad Request
type LoadPortalLinksPagedBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &LoadPortalLinksPagedBadRequestError{}

func (e *LoadPortalLinksPagedBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type LoadPortalLinksPagedData struct {
	Content    []PortalLinkResponse `json:"content,omitempty"`
	Pagination *PaginationData      `json:"pagination,omitempty"`
}

func (l *LoadPortalLinksPagedData) GetContent() []PortalLinkResponse {
	if l == nil {
		return nil
	}
	return l.Content
}

func (l *LoadPortalLinksPagedData) GetPagination() *PaginationData {
	if l == nil {
		return nil
	}
	return l.Pagination
}

// LoadPortalLinksPagedResponseBody - OK
type LoadPortalLinksPagedResponseBody struct {
	Message *string                   `json:"message,omitempty"`
	Status  *bool                     `json:"status,omitempty"`
	Data    *LoadPortalLinksPagedData `json:"data,omitempty"`
}

func (l *LoadPortalLinksPagedResponseBody) GetMessage() *string {
	if l == nil {
		return nil
	}
	return l.Message
}

func (l *LoadPortalLinksPagedResponseBody) GetStatus() *bool {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LoadPortalLinksPagedResponseBody) GetData() *LoadPortalLinksPagedData {
	if l == nil {
		return nil
	}
	return l.Data
}

type LoadPortalLinksPagedResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *LoadPortalLinksPagedResponseBody
}

func (l *LoadPortalLinksPagedResponse) GetHTTPMeta() HTTPMetadata {
	if l == nil {
		return HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LoadPortalLinksPagedResponse) GetObject() *LoadPortalLinksPagedResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
