// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type MetaEventResponse struct {
	Attempt   *MetaEventAttempt    `json:"attempt,omitempty"`
	CreatedAt *string              `json:"created_at,omitempty"`
	DeletedAt *string              `json:"deleted_at,omitempty"`
	EventType *string              `json:"event_type,omitempty"`
	Metadata  *Metadata            `json:"metadata,omitempty"`
	ProjectID *string              `json:"project_id,omitempty"`
	Status    *EventDeliveryStatus `json:"status,omitempty"`
	UID       *string              `json:"uid,omitempty"`
	UpdatedAt *string              `json:"updated_at,omitempty"`
}

func (o *MetaEventResponse) GetAttempt() *MetaEventAttempt {
	if o == nil {
		return nil
	}
	return o.Attempt
}

func (o *MetaEventResponse) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *MetaEventResponse) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *MetaEventResponse) GetEventType() *string {
	if o == nil {
		return nil
	}
	return o.EventType
}

func (o *MetaEventResponse) GetMetadata() *Metadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *MetaEventResponse) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *MetaEventResponse) GetStatus() *EventDeliveryStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *MetaEventResponse) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *MetaEventResponse) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
