// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type PaginationData struct {
	HasNextPage    *bool   `json:"has_next_page,omitempty"`
	HasPrevPage    *bool   `json:"has_prev_page,omitempty"`
	NextPageCursor *string `json:"next_page_cursor,omitempty"`
	PerPage        *int64  `json:"per_page,omitempty"`
	PrevPageCursor *string `json:"prev_page_cursor,omitempty"`
}

func (o *PaginationData) GetHasNextPage() *bool {
	if o == nil {
		return nil
	}
	return o.HasNextPage
}

func (o *PaginationData) GetHasPrevPage() *bool {
	if o == nil {
		return nil
	}
	return o.HasPrevPage
}

func (o *PaginationData) GetNextPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextPageCursor
}

func (o *PaginationData) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *PaginationData) GetPrevPageCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevPageCursor
}
