// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type PaginationData struct {
	HasNextPage    *bool   `json:"has_next_page,omitempty"`
	HasPrevPage    *bool   `json:"has_prev_page,omitempty"`
	NextPageCursor *string `json:"next_page_cursor,omitempty"`
	PerPage        *int64  `json:"per_page,omitempty"`
	PrevPageCursor *string `json:"prev_page_cursor,omitempty"`
}

func (p *PaginationData) GetHasNextPage() *bool {
	if p == nil {
		return nil
	}
	return p.HasNextPage
}

func (p *PaginationData) GetHasPrevPage() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrevPage
}

func (p *PaginationData) GetNextPageCursor() *string {
	if p == nil {
		return nil
	}
	return p.NextPageCursor
}

func (p *PaginationData) GetPerPage() *int64 {
	if p == nil {
		return nil
	}
	return p.PerPage
}

func (p *PaginationData) GetPrevPageCursor() *string {
	if p == nil {
		return nil
	}
	return p.PrevPageCursor
}
