// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type PauseEndpointRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Endpoint ID
	EndpointID string `pathParam:"style=simple,explode=false,name=endpointID"`
}

func (p *PauseEndpointRequest) GetProjectID() string {
	if p == nil {
		return ""
	}
	return p.ProjectID
}

func (p *PauseEndpointRequest) GetEndpointID() string {
	if p == nil {
		return ""
	}
	return p.EndpointID
}

// PauseEndpointNotFoundError - Not Found
type PauseEndpointNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &PauseEndpointNotFoundError{}

func (e *PauseEndpointNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PauseEndpointUnauthorizedError - Unauthorized
type PauseEndpointUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &PauseEndpointUnauthorizedError{}

func (e *PauseEndpointUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PauseEndpointBadRequestError - Bad Request
type PauseEndpointBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &PauseEndpointBadRequestError{}

func (e *PauseEndpointBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PauseEndpointResponseBody - Accepted
type PauseEndpointResponseBody struct {
	Message *string           `json:"message,omitempty"`
	Status  *bool             `json:"status,omitempty"`
	Data    *EndpointResponse `json:"data,omitempty"`
}

func (p *PauseEndpointResponseBody) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

func (p *PauseEndpointResponseBody) GetStatus() *bool {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PauseEndpointResponseBody) GetData() *EndpointResponse {
	if p == nil {
		return nil
	}
	return p.Data
}

type PauseEndpointResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Accepted
	Object *PauseEndpointResponseBody
}

func (p *PauseEndpointResponse) GetHTTPMeta() HTTPMetadata {
	if p == nil {
		return HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PauseEndpointResponse) GetObject() *PauseEndpointResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
