// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type PortalLink struct {
	// Specify whether endpoint management can be done through the Portal Link UI
	CanManageEndpoint *bool `json:"can_manage_endpoint,omitempty"`
	// IDs of endpoints in this portal link
	Endpoints []string `json:"endpoints,omitempty"`
	// Portal Link Name
	Name *string `json:"name,omitempty"`
	// Alternatively specify OwnerID, the portal link will inherit all the endpoints with this owner ID
	OwnerID *string `json:"owner_id,omitempty"`
}

func (o *PortalLink) GetCanManageEndpoint() *bool {
	if o == nil {
		return nil
	}
	return o.CanManageEndpoint
}

func (o *PortalLink) GetEndpoints() []string {
	if o == nil {
		return nil
	}
	return o.Endpoints
}

func (o *PortalLink) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PortalLink) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}
