// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type ProviderConfig struct {
	Twitter *TwitterProviderConfig `json:"twitter,omitempty"`
}

func (p *ProviderConfig) GetTwitter() *TwitterProviderConfig {
	if p == nil {
		return nil
	}
	return p.Twitter
}
