// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type PubSubConfig struct {
	Amqp    *AmqpPubSubconfig   `json:"amqp,omitempty"`
	Google  *GooglePubSubConfig `json:"google,omitempty"`
	Kafka   *KafkaPubSubConfig  `json:"kafka,omitempty"`
	Sqs     *SQSPubSubConfig    `json:"sqs,omitempty"`
	Type    *PubSubType         `json:"type,omitempty"`
	Workers *int64              `json:"workers,omitempty"`
}

func (o *PubSubConfig) GetAmqp() *AmqpPubSubconfig {
	if o == nil {
		return nil
	}
	return o.Amqp
}

func (o *PubSubConfig) GetGoogle() *GooglePubSubConfig {
	if o == nil {
		return nil
	}
	return o.Google
}

func (o *PubSubConfig) GetKafka() *KafkaPubSubConfig {
	if o == nil {
		return nil
	}
	return o.Kafka
}

func (o *PubSubConfig) GetSqs() *SQSPubSubConfig {
	if o == nil {
		return nil
	}
	return o.Sqs
}

func (o *PubSubConfig) GetType() *PubSubType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *PubSubConfig) GetWorkers() *int64 {
	if o == nil {
		return nil
	}
	return o.Workers
}
