// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type PubSubConfig struct {
	Amqp    *AmqpPubSubconfig   `json:"amqp,omitempty"`
	Google  *GooglePubSubConfig `json:"google,omitempty"`
	Kafka   *KafkaPubSubConfig  `json:"kafka,omitempty"`
	Sqs     *SQSPubSubConfig    `json:"sqs,omitempty"`
	Type    *PubSubType         `json:"type,omitempty"`
	Workers *int64              `json:"workers,omitempty"`
}

func (p *PubSubConfig) GetAmqp() *AmqpPubSubconfig {
	if p == nil {
		return nil
	}
	return p.Amqp
}

func (p *PubSubConfig) GetGoogle() *GooglePubSubConfig {
	if p == nil {
		return nil
	}
	return p.Google
}

func (p *PubSubConfig) GetKafka() *KafkaPubSubConfig {
	if p == nil {
		return nil
	}
	return p.Kafka
}

func (p *PubSubConfig) GetSqs() *SQSPubSubConfig {
	if p == nil {
		return nil
	}
	return p.Sqs
}

func (p *PubSubConfig) GetType() *PubSubType {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PubSubConfig) GetWorkers() *int64 {
	if p == nil {
		return nil
	}
	return p.Workers
}
