// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type PubSubType string

const (
	PubSubTypeSqs    PubSubType = "sqs"
	PubSubTypeGoogle PubSubType = "google"
	PubSubTypeKafka  PubSubType = "kafka"
	PubSubTypeAmqp   PubSubType = "amqp"
)

func (e PubSubType) ToPointer() *PubSubType {
	return &e
}
func (e *PubSubType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sqs":
		fallthrough
	case "google":
		fallthrough
	case "kafka":
		fallthrough
	case "amqp":
		*e = PubSubType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PubSubType: %v", v)
	}
}
