// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type RateLimitConfiguration struct {
	Count    *int64 `json:"count,omitempty"`
	Duration *int64 `json:"duration,omitempty"`
}

func (o *RateLimitConfiguration) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *RateLimitConfiguration) GetDuration() *int64 {
	if o == nil {
		return nil
	}
	return o.Duration
}
