// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type RefreshPortalLinkAuthTokenRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// portal link id
	PortalLinkID string `pathParam:"style=simple,explode=false,name=portalLinkID"`
}

func (o *RefreshPortalLinkAuthTokenRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *RefreshPortalLinkAuthTokenRequest) GetPortalLinkID() string {
	if o == nil {
		return ""
	}
	return o.PortalLinkID
}

// RefreshPortalLinkAuthTokenNotFoundError - Not Found
type RefreshPortalLinkAuthTokenNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &RefreshPortalLinkAuthTokenNotFoundError{}

func (e *RefreshPortalLinkAuthTokenNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// RefreshPortalLinkAuthTokenUnauthorizedError - Unauthorized
type RefreshPortalLinkAuthTokenUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &RefreshPortalLinkAuthTokenUnauthorizedError{}

func (e *RefreshPortalLinkAuthTokenUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// RefreshPortalLinkAuthTokenBadRequestError - Bad Request
type RefreshPortalLinkAuthTokenBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &RefreshPortalLinkAuthTokenBadRequestError{}

func (e *RefreshPortalLinkAuthTokenBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// RefreshPortalLinkAuthTokenResponseBody - OK
type RefreshPortalLinkAuthTokenResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *string `json:"data,omitempty"`
}

func (o *RefreshPortalLinkAuthTokenResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *RefreshPortalLinkAuthTokenResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *RefreshPortalLinkAuthTokenResponseBody) GetData() *string {
	if o == nil {
		return nil
	}
	return o.Data
}

type RefreshPortalLinkAuthTokenResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *RefreshPortalLinkAuthTokenResponseBody
}

func (o *RefreshPortalLinkAuthTokenResponse) GetHTTPMeta() HTTPMetadata {
	if o == nil {
		return HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RefreshPortalLinkAuthTokenResponse) GetObject() *RefreshPortalLinkAuthTokenResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
