// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type ReplayEndpointEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// event id
	EventID string `pathParam:"style=simple,explode=false,name=eventID"`
}

func (r *ReplayEndpointEventRequest) GetProjectID() string {
	if r == nil {
		return ""
	}
	return r.ProjectID
}

func (r *ReplayEndpointEventRequest) GetEventID() string {
	if r == nil {
		return ""
	}
	return r.EventID
}

// ReplayEndpointEventNotFoundError - Not Found
type ReplayEndpointEventNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ReplayEndpointEventNotFoundError{}

func (e *ReplayEndpointEventNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ReplayEndpointEventUnauthorizedError - Unauthorized
type ReplayEndpointEventUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ReplayEndpointEventUnauthorizedError{}

func (e *ReplayEndpointEventUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ReplayEndpointEventBadRequestError - Bad Request
type ReplayEndpointEventBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &ReplayEndpointEventBadRequestError{}

func (e *ReplayEndpointEventBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ReplayEndpointEventResponseBody - OK
type ReplayEndpointEventResponseBody struct {
	Message *string        `json:"message,omitempty"`
	Status  *bool          `json:"status,omitempty"`
	Data    *EventResponse `json:"data,omitempty"`
}

func (r *ReplayEndpointEventResponseBody) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *ReplayEndpointEventResponseBody) GetStatus() *bool {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *ReplayEndpointEventResponseBody) GetData() *EventResponse {
	if r == nil {
		return nil
	}
	return r.Data
}

type ReplayEndpointEventResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *ReplayEndpointEventResponseBody
}

func (r *ReplayEndpointEventResponse) GetHTTPMeta() HTTPMetadata {
	if r == nil {
		return HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReplayEndpointEventResponse) GetObject() *ReplayEndpointEventResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
