// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type RevokePortalLinkRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// portal link id
	PortalLinkID string `pathParam:"style=simple,explode=false,name=portalLinkID"`
}

func (r *RevokePortalLinkRequest) GetProjectID() string {
	if r == nil {
		return ""
	}
	return r.ProjectID
}

func (r *RevokePortalLinkRequest) GetPortalLinkID() string {
	if r == nil {
		return ""
	}
	return r.PortalLinkID
}

// RevokePortalLinkNotFoundError - Not Found
type RevokePortalLinkNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &RevokePortalLinkNotFoundError{}

func (e *RevokePortalLinkNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// RevokePortalLinkUnauthorizedError - Unauthorized
type RevokePortalLinkUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &RevokePortalLinkUnauthorizedError{}

func (e *RevokePortalLinkUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// RevokePortalLinkBadRequestError - Bad Request
type RevokePortalLinkBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &RevokePortalLinkBadRequestError{}

func (e *RevokePortalLinkBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// RevokePortalLinkResponseBody - OK
type RevokePortalLinkResponseBody struct {
	Message *string `json:"message,omitempty"`
	Status  *bool   `json:"status,omitempty"`
	Data    *Object `json:"data,omitempty"`
}

func (r *RevokePortalLinkResponseBody) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

func (r *RevokePortalLinkResponseBody) GetStatus() *bool {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *RevokePortalLinkResponseBody) GetData() *Object {
	if r == nil {
		return nil
	}
	return r.Data
}

type RevokePortalLinkResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *RevokePortalLinkResponseBody
}

func (r *RevokePortalLinkResponse) GetHTTPMeta() HTTPMetadata {
	if r == nil {
		return HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RevokePortalLinkResponse) GetObject() *RevokePortalLinkResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
