// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type Security struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=convoy_bearer_auth"`
}

func (s *Security) GetBearerAuth() *string {
	if s == nil {
		return nil
	}
	return s.BearerAuth
}
