// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type SourceType string

const (
	SourceTypeHTTP           SourceType = "http"
	SourceTypeRestAPI        SourceType = "rest_api"
	SourceTypePubSub         SourceType = "pub_sub"
	SourceTypeDbChangeStream SourceType = "db_change_stream"
)

func (e SourceType) ToPointer() *SourceType {
	return &e
}
func (e *SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		fallthrough
	case "rest_api":
		fallthrough
	case "pub_sub":
		fallthrough
	case "db_change_stream":
		*e = SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceType: %v", v)
	}
}
