// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type SourceProvider string

const (
	SourceProviderGithub  SourceProvider = "github"
	SourceProviderTwitter SourceProvider = "twitter"
	SourceProviderShopify SourceProvider = "shopify"
)

func (e SourceProvider) ToPointer() *SourceProvider {
	return &e
}
func (e *SourceProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "github":
		fallthrough
	case "twitter":
		fallthrough
	case "shopify":
		*e = SourceProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceProvider: %v", v)
	}
}
