// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type Source struct {
	BodyFunction    *string         `json:"body_function,omitempty"`
	CreatedAt       *string         `json:"created_at,omitempty"`
	CustomResponse  *CustomResponse `json:"custom_response,omitempty"`
	DeletedAt       *string         `json:"deleted_at,omitempty"`
	ForwardHeaders  []string        `json:"forward_headers,omitempty"`
	HeaderFunction  *string         `json:"header_function,omitempty"`
	IdempotencyKeys []string        `json:"idempotency_keys,omitempty"`
	IsDisabled      *bool           `json:"is_disabled,omitempty"`
	MaskID          *string         `json:"mask_id,omitempty"`
	Name            *string         `json:"name,omitempty"`
	ProjectID       *string         `json:"project_id,omitempty"`
	Provider        *SourceProvider `json:"provider,omitempty"`
	ProviderConfig  *ProviderConfig `json:"provider_config,omitempty"`
	PubSub          *PubSubConfig   `json:"pub_sub,omitempty"`
	Type            *SourceType     `json:"type,omitempty"`
	UID             *string         `json:"uid,omitempty"`
	UpdatedAt       *string         `json:"updated_at,omitempty"`
	URL             *string         `json:"url,omitempty"`
	Verifier        *VerifierConfig `json:"verifier,omitempty"`
}

func (s *Source) GetBodyFunction() *string {
	if s == nil {
		return nil
	}
	return s.BodyFunction
}

func (s *Source) GetCreatedAt() *string {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *Source) GetCustomResponse() *CustomResponse {
	if s == nil {
		return nil
	}
	return s.CustomResponse
}

func (s *Source) GetDeletedAt() *string {
	if s == nil {
		return nil
	}
	return s.DeletedAt
}

func (s *Source) GetForwardHeaders() []string {
	if s == nil {
		return nil
	}
	return s.ForwardHeaders
}

func (s *Source) GetHeaderFunction() *string {
	if s == nil {
		return nil
	}
	return s.HeaderFunction
}

func (s *Source) GetIdempotencyKeys() []string {
	if s == nil {
		return nil
	}
	return s.IdempotencyKeys
}

func (s *Source) GetIsDisabled() *bool {
	if s == nil {
		return nil
	}
	return s.IsDisabled
}

func (s *Source) GetMaskID() *string {
	if s == nil {
		return nil
	}
	return s.MaskID
}

func (s *Source) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *Source) GetProjectID() *string {
	if s == nil {
		return nil
	}
	return s.ProjectID
}

func (s *Source) GetProvider() *SourceProvider {
	if s == nil {
		return nil
	}
	return s.Provider
}

func (s *Source) GetProviderConfig() *ProviderConfig {
	if s == nil {
		return nil
	}
	return s.ProviderConfig
}

func (s *Source) GetPubSub() *PubSubConfig {
	if s == nil {
		return nil
	}
	return s.PubSub
}

func (s *Source) GetType() *SourceType {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *Source) GetUID() *string {
	if s == nil {
		return nil
	}
	return s.UID
}

func (s *Source) GetUpdatedAt() *string {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *Source) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *Source) GetVerifier() *VerifierConfig {
	if s == nil {
		return nil
	}
	return s.Verifier
}
