// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type SQSPubSubConfig struct {
	AccessKeyID   *string `json:"access_key_id,omitempty"`
	DefaultRegion *string `json:"default_region,omitempty"`
	QueueName     *string `json:"queue_name,omitempty"`
	SecretKey     *string `json:"secret_key,omitempty"`
}

func (o *SQSPubSubConfig) GetAccessKeyID() *string {
	if o == nil {
		return nil
	}
	return o.AccessKeyID
}

func (o *SQSPubSubConfig) GetDefaultRegion() *string {
	if o == nil {
		return nil
	}
	return o.DefaultRegion
}

func (o *SQSPubSubConfig) GetQueueName() *string {
	if o == nil {
		return nil
	}
	return o.QueueName
}

func (o *SQSPubSubConfig) GetSecretKey() *string {
	if o == nil {
		return nil
	}
	return o.SecretKey
}
