// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type SubscriptionResponse struct {
	// subscription config
	AlertConfig      *AlertConfiguration     `json:"alert_config,omitempty"`
	CreatedAt        *string                 `json:"created_at,omitempty"`
	DeletedAt        *string                 `json:"deleted_at,omitempty"`
	DeliveryMode     *DeliveryMode           `json:"delivery_mode,omitempty"`
	DeviceMetadata   *Device                 `json:"device_metadata,omitempty"`
	EndpointMetadata *Endpoint               `json:"endpoint_metadata,omitempty"`
	FilterConfig     *FilterConfiguration    `json:"filter_config,omitempty"`
	Function         *string                 `json:"function,omitempty"`
	Name             *string                 `json:"name,omitempty"`
	ProjectID        *string                 `json:"project_id,omitempty"`
	RateLimitConfig  *RateLimitConfiguration `json:"rate_limit_config,omitempty"`
	RetryConfig      *RetryConfiguration     `json:"retry_config,omitempty"`
	SourceMetadata   *Source                 `json:"source_metadata,omitempty"`
	Type             *SubscriptionType       `json:"type,omitempty"`
	UID              *string                 `json:"uid,omitempty"`
	UpdatedAt        *string                 `json:"updated_at,omitempty"`
}

func (o *SubscriptionResponse) GetAlertConfig() *AlertConfiguration {
	if o == nil {
		return nil
	}
	return o.AlertConfig
}

func (o *SubscriptionResponse) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *SubscriptionResponse) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *SubscriptionResponse) GetDeliveryMode() *DeliveryMode {
	if o == nil {
		return nil
	}
	return o.DeliveryMode
}

func (o *SubscriptionResponse) GetDeviceMetadata() *Device {
	if o == nil {
		return nil
	}
	return o.DeviceMetadata
}

func (o *SubscriptionResponse) GetEndpointMetadata() *Endpoint {
	if o == nil {
		return nil
	}
	return o.EndpointMetadata
}

func (o *SubscriptionResponse) GetFilterConfig() *FilterConfiguration {
	if o == nil {
		return nil
	}
	return o.FilterConfig
}

func (o *SubscriptionResponse) GetFunction() *string {
	if o == nil {
		return nil
	}
	return o.Function
}

func (o *SubscriptionResponse) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *SubscriptionResponse) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *SubscriptionResponse) GetRateLimitConfig() *RateLimitConfiguration {
	if o == nil {
		return nil
	}
	return o.RateLimitConfig
}

func (o *SubscriptionResponse) GetRetryConfig() *RetryConfiguration {
	if o == nil {
		return nil
	}
	return o.RetryConfig
}

func (o *SubscriptionResponse) GetSourceMetadata() *Source {
	if o == nil {
		return nil
	}
	return o.SourceMetadata
}

func (o *SubscriptionResponse) GetType() *SubscriptionType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *SubscriptionResponse) GetUID() *string {
	if o == nil {
		return nil
	}
	return o.UID
}

func (o *SubscriptionResponse) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
