// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type TestFilter struct {
	// Same Request & Headers
	Request *FilterSchema `json:"request,omitempty"`
	// Sample test schema
	Schema *FilterSchema `json:"schema,omitempty"`
}

func (t *TestFilter) GetRequest() *FilterSchema {
	if t == nil {
		return nil
	}
	return t.Request
}

func (t *TestFilter) GetSchema() *FilterSchema {
	if t == nil {
		return nil
	}
	return t.Schema
}
