// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b5ca03b5bf6c

package convoy

type TestFilterResponse struct {
	// Whether the payload matches the filter criteria
	IsMatch *bool `json:"is_match,omitempty"`
}

func (t *TestFilterResponse) GetIsMatch() *bool {
	if t == nil {
		return nil
	}
	return t.IsMatch
}
