// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type TestFilterRequest struct {
	// Sample payload to test against the filter (required)
	Payload any `json:"payload"`
}

func (o *TestFilterRequest) GetPayload() any {
	if o == nil {
		return nil
	}
	return o.Payload
}
