// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type TestSubscriptionFunctionRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Function Details
	FunctionRequest FunctionRequest `request:"mediaType=application/json"`
}

func (t *TestSubscriptionFunctionRequest) GetProjectID() string {
	if t == nil {
		return ""
	}
	return t.ProjectID
}

func (t *TestSubscriptionFunctionRequest) GetFunctionRequest() FunctionRequest {
	if t == nil {
		return FunctionRequest{}
	}
	return t.FunctionRequest
}

// TestSubscriptionFunctionNotFoundError - Not Found
type TestSubscriptionFunctionNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &TestSubscriptionFunctionNotFoundError{}

func (e *TestSubscriptionFunctionNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TestSubscriptionFunctionUnauthorizedError - Unauthorized
type TestSubscriptionFunctionUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &TestSubscriptionFunctionUnauthorizedError{}

func (e *TestSubscriptionFunctionUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TestSubscriptionFunctionBadRequestError - Bad Request
type TestSubscriptionFunctionBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &TestSubscriptionFunctionBadRequestError{}

func (e *TestSubscriptionFunctionBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TestSubscriptionFunctionResponseBody - OK
type TestSubscriptionFunctionResponseBody struct {
	Message *string           `json:"message,omitempty"`
	Status  *bool             `json:"status,omitempty"`
	Data    *FunctionResponse `json:"data,omitempty"`
}

func (t *TestSubscriptionFunctionResponseBody) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

func (t *TestSubscriptionFunctionResponseBody) GetStatus() *bool {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TestSubscriptionFunctionResponseBody) GetData() *FunctionResponse {
	if t == nil {
		return nil
	}
	return t.Data
}

type TestSubscriptionFunctionResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *TestSubscriptionFunctionResponseBody
}

func (t *TestSubscriptionFunctionResponse) GetHTTPMeta() HTTPMetadata {
	if t == nil {
		return HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TestSubscriptionFunctionResponse) GetObject() *TestSubscriptionFunctionResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
