// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type TestFilter struct {
	// Same Request & Headers
	Request *FilterSchema `json:"request,omitempty"`
	// Sample test schema
	Schema *FilterSchema `json:"schema,omitempty"`
}

func (o *TestFilter) GetRequest() *FilterSchema {
	if o == nil {
		return nil
	}
	return o.Request
}

func (o *TestFilter) GetSchema() *FilterSchema {
	if o == nil {
		return nil
	}
	return o.Schema
}
