// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type TwitterProviderConfig struct {
	CrcVerifiedAt *string `json:"crc_verified_at,omitempty"`
}

func (t *TwitterProviderConfig) GetCrcVerifiedAt() *string {
	if t == nil {
		return nil
	}
	return t.CrcVerifiedAt
}
