// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

// UpdateSubscriptionDeliveryMode - Delivery mode configuration
type UpdateSubscriptionDeliveryMode string

const (
	UpdateSubscriptionDeliveryModeAtLeastOnce UpdateSubscriptionDeliveryMode = "at_least_once"
	UpdateSubscriptionDeliveryModeAtMostOnce  UpdateSubscriptionDeliveryMode = "at_most_once"
)

func (e UpdateSubscriptionDeliveryMode) ToPointer() *UpdateSubscriptionDeliveryMode {
	return &e
}

type UpdateSubscription struct {
	// Alert configuration
	AlertConfig *AlertConfiguration `json:"alert_config,omitempty"`
	// Deprecated but necessary for backward compatibility
	AppID *string `json:"app_id,omitempty"`
	// Delivery mode configuration
	DeliveryMode *UpdateSubscriptionDeliveryMode `json:"delivery_mode,omitempty"`
	// Destination endpoint ID
	EndpointID *string `json:"endpoint_id,omitempty"`
	// Filter configuration
	FilterConfig *FilterConfiguration `json:"filter_config,omitempty"`
	// Convoy supports mutating your request payload using a js function. Use this field
	// to specify a `transform` function for this purpose. See this[https://docs.getconvoy.io/product-manual/subscriptions#functions] for more
	Function *string `json:"function,omitempty"`
	// Subscription Nme
	Name *string `json:"name,omitempty"`
	// Rate limit configuration
	RateLimitConfig *RateLimitConfiguration `json:"rate_limit_config,omitempty"`
	// Retry configuration
	RetryConfig *RetryConfiguration `json:"retry_config,omitempty"`
	// Source Id
	SourceID *string `json:"source_id,omitempty"`
}

func (u *UpdateSubscription) GetAlertConfig() *AlertConfiguration {
	if u == nil {
		return nil
	}
	return u.AlertConfig
}

func (u *UpdateSubscription) GetAppID() *string {
	if u == nil {
		return nil
	}
	return u.AppID
}

func (u *UpdateSubscription) GetDeliveryMode() *UpdateSubscriptionDeliveryMode {
	if u == nil {
		return nil
	}
	return u.DeliveryMode
}

func (u *UpdateSubscription) GetEndpointID() *string {
	if u == nil {
		return nil
	}
	return u.EndpointID
}

func (u *UpdateSubscription) GetFilterConfig() *FilterConfiguration {
	if u == nil {
		return nil
	}
	return u.FilterConfig
}

func (u *UpdateSubscription) GetFunction() *string {
	if u == nil {
		return nil
	}
	return u.Function
}

func (u *UpdateSubscription) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSubscription) GetRateLimitConfig() *RateLimitConfiguration {
	if u == nil {
		return nil
	}
	return u.RateLimitConfig
}

func (u *UpdateSubscription) GetRetryConfig() *RetryConfiguration {
	if u == nil {
		return nil
	}
	return u.RetryConfig
}

func (u *UpdateSubscription) GetSourceID() *string {
	if u == nil {
		return nil
	}
	return u.SourceID
}
