// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type UpdateEndpoint struct {
	// Convoy supports two [signature formats](https://getconvoy.io/docs/product-manual/signatures)
	// -- simple or advanced. If left unspecified, we default to false.
	AdvancedSignatures *bool `json:"advanced_signatures,omitempty"`
	// This is used to define any custom authentication required by the endpoint. This
	// shouldn't be needed often because webhook endpoints usually should be exposed to
	// the internet.
	Authentication *EndpointAuthentication `json:"authentication,omitempty"`
	// Human-readable description of the endpoint. Think of this as metadata describing
	// the endpoint
	Description *string `json:"description,omitempty"`
	// Define endpoint http timeout in seconds.
	HTTPTimeout *int64 `json:"http_timeout,omitempty"`
	// This is used to manually enable/disable the endpoint.
	IsDisabled *bool   `json:"is_disabled,omitempty"`
	Name       *string `json:"name,omitempty"`
	// The OwnerID is used to group more than one endpoint together to achieve
	// [fanout](https://getconvoy.io/docs/manual/endpoints#Endpoint%20Owner%20ID)
	OwnerID *string `json:"owner_id,omitempty"`
	// Rate limit is the total number of requests to be sent to an endpoint in
	// the time duration specified in RateLimitDuration
	RateLimit *int64 `json:"rate_limit,omitempty"`
	// Rate limit duration specifies the time range for the rate limit.
	RateLimitDuration *int64 `json:"rate_limit_duration,omitempty"`
	// Endpoint's webhook secret. If not provided, Convoy autogenerates one for the endpoint.
	Secret *string `json:"secret,omitempty"`
	// Slack webhook URL is an alternative method to support email where endpoint developers
	// can receive failure notifications on a slack channel.
	SlackWebhookURL *string `json:"slack_webhook_url,omitempty"`
	// Endpoint developers support email. This is used for communicating endpoint state
	// changes. You should always turn this on when disabling endpoints are enabled.
	SupportEmail *string `json:"support_email,omitempty"`
	// URL is the endpoint's URL prefixed with https. non-https urls are currently
	// not supported.
	URL *string `json:"url,omitempty"`
}

func (u *UpdateEndpoint) GetAdvancedSignatures() *bool {
	if u == nil {
		return nil
	}
	return u.AdvancedSignatures
}

func (u *UpdateEndpoint) GetAuthentication() *EndpointAuthentication {
	if u == nil {
		return nil
	}
	return u.Authentication
}

func (u *UpdateEndpoint) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateEndpoint) GetHTTPTimeout() *int64 {
	if u == nil {
		return nil
	}
	return u.HTTPTimeout
}

func (u *UpdateEndpoint) GetIsDisabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsDisabled
}

func (u *UpdateEndpoint) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateEndpoint) GetOwnerID() *string {
	if u == nil {
		return nil
	}
	return u.OwnerID
}

func (u *UpdateEndpoint) GetRateLimit() *int64 {
	if u == nil {
		return nil
	}
	return u.RateLimit
}

func (u *UpdateEndpoint) GetRateLimitDuration() *int64 {
	if u == nil {
		return nil
	}
	return u.RateLimitDuration
}

func (u *UpdateEndpoint) GetSecret() *string {
	if u == nil {
		return nil
	}
	return u.Secret
}

func (u *UpdateEndpoint) GetSlackWebhookURL() *string {
	if u == nil {
		return nil
	}
	return u.SlackWebhookURL
}

func (u *UpdateEndpoint) GetSupportEmail() *string {
	if u == nil {
		return nil
	}
	return u.SupportEmail
}

func (u *UpdateEndpoint) GetURL() *string {
	if u == nil {
		return nil
	}
	return u.URL
}
