// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type UpdateSourceRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// source id
	SourceID string `pathParam:"style=simple,explode=false,name=sourceID"`
	// Source Details
	UpdateSource UpdateSource `request:"mediaType=application/json"`
}

func (u *UpdateSourceRequest) GetProjectID() string {
	if u == nil {
		return ""
	}
	return u.ProjectID
}

func (u *UpdateSourceRequest) GetSourceID() string {
	if u == nil {
		return ""
	}
	return u.SourceID
}

func (u *UpdateSourceRequest) GetUpdateSource() UpdateSource {
	if u == nil {
		return UpdateSource{}
	}
	return u.UpdateSource
}

// UpdateSourceNotFoundError - Not Found
type UpdateSourceNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateSourceNotFoundError{}

func (e *UpdateSourceNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateSourceUnauthorizedError - Unauthorized
type UpdateSourceUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateSourceUnauthorizedError{}

func (e *UpdateSourceUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateSourceBadRequestError - Bad Request
type UpdateSourceBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateSourceBadRequestError{}

func (e *UpdateSourceBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateSourceResponseBody - Accepted
type UpdateSourceResponseBody struct {
	Message *string         `json:"message,omitempty"`
	Status  *bool           `json:"status,omitempty"`
	Data    *SourceResponse `json:"data,omitempty"`
}

func (u *UpdateSourceResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateSourceResponseBody) GetStatus() *bool {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateSourceResponseBody) GetData() *SourceResponse {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateSourceResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Accepted
	Object *UpdateSourceResponseBody
}

func (u *UpdateSourceResponse) GetHTTPMeta() HTTPMetadata {
	if u == nil {
		return HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSourceResponse) GetObject() *UpdateSourceResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
