// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type UpdateEventType struct {
	// Category is a product-specific grouping for the event type
	Category *string `json:"category,omitempty"`
	// Description is used to describe what the event type does
	Description *string `json:"description,omitempty"`
	// JSONSchema is the JSON structure of the event type
	JSONSchema map[string]any `json:"json_schema,omitempty"`
}

func (u *UpdateEventType) GetCategory() *string {
	if u == nil {
		return nil
	}
	return u.Category
}

func (u *UpdateEventType) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateEventType) GetJSONSchema() map[string]any {
	if u == nil {
		return nil
	}
	return u.JSONSchema
}
