// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type UpdateSource struct {
	// Function is a javascript function used to mutate the payload
	// immediately after ingesting an event
	BodyFunction *string `json:"body_function,omitempty"`
	// Custom response is used to define a custom response for incoming
	// webhooks project sources only.
	CustomResponse *UpdateCustomResponse `json:"custom_response,omitempty"`
	// Soecfy header you want convoy to save from the ingest request and forward to your endpoints when the event is dispatched.
	ForwardHeaders []string `json:"forward_headers,omitempty"`
	// Function is a javascript function used to mutate the headers
	// immediately after ingesting an event
	HeaderFunction *string `json:"header_function,omitempty"`
	// IdempotencyKeys are used to specify parts of a webhook request to uniquely
	// identify the event in an incoming webhooks project.
	IdempotencyKeys []string `json:"idempotency_keys,omitempty"`
	// This is used to manually enable/disable the source.
	IsDisabled *bool `json:"is_disabled,omitempty"`
	// Source name.
	Name *string `json:"name,omitempty"`
	// PubSub are used to specify message broker sources for outgoing
	// webhooks projects, you only need to specify this when the source type is `pub_sub`.
	PubSub *PubSubConfig `json:"pub_sub,omitempty"`
	// Source Type.
	Type *SourceType `json:"type,omitempty"`
	// Verifiers are used to verify webhook events ingested in incoming
	// webhooks projects.  If set, type is required and match the verifier
	// type object you choose.
	Verifier *VerifierConfig `json:"verifier,omitempty"`
}

func (u *UpdateSource) GetBodyFunction() *string {
	if u == nil {
		return nil
	}
	return u.BodyFunction
}

func (u *UpdateSource) GetCustomResponse() *UpdateCustomResponse {
	if u == nil {
		return nil
	}
	return u.CustomResponse
}

func (u *UpdateSource) GetForwardHeaders() []string {
	if u == nil {
		return nil
	}
	return u.ForwardHeaders
}

func (u *UpdateSource) GetHeaderFunction() *string {
	if u == nil {
		return nil
	}
	return u.HeaderFunction
}

func (u *UpdateSource) GetIdempotencyKeys() []string {
	if u == nil {
		return nil
	}
	return u.IdempotencyKeys
}

func (u *UpdateSource) GetIsDisabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsDisabled
}

func (u *UpdateSource) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSource) GetPubSub() *PubSubConfig {
	if u == nil {
		return nil
	}
	return u.PubSub
}

func (u *UpdateSource) GetType() *SourceType {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateSource) GetVerifier() *VerifierConfig {
	if u == nil {
		return nil
	}
	return u.Verifier
}
