// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type UpdatePortalLinkRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// portal link id
	PortalLinkID string `pathParam:"style=simple,explode=false,name=portalLinkID"`
	// Portal Link Details
	PortalLink PortalLink `request:"mediaType=application/json"`
}

func (u *UpdatePortalLinkRequest) GetProjectID() string {
	if u == nil {
		return ""
	}
	return u.ProjectID
}

func (u *UpdatePortalLinkRequest) GetPortalLinkID() string {
	if u == nil {
		return ""
	}
	return u.PortalLinkID
}

func (u *UpdatePortalLinkRequest) GetPortalLink() PortalLink {
	if u == nil {
		return PortalLink{}
	}
	return u.PortalLink
}

// UpdatePortalLinkNotFoundError - Not Found
type UpdatePortalLinkNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdatePortalLinkNotFoundError{}

func (e *UpdatePortalLinkNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdatePortalLinkUnauthorizedError - Unauthorized
type UpdatePortalLinkUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdatePortalLinkUnauthorizedError{}

func (e *UpdatePortalLinkUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdatePortalLinkBadRequestError - Bad Request
type UpdatePortalLinkBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdatePortalLinkBadRequestError{}

func (e *UpdatePortalLinkBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdatePortalLinkResponseBody - Accepted
type UpdatePortalLinkResponseBody struct {
	Message *string             `json:"message,omitempty"`
	Status  *bool               `json:"status,omitempty"`
	Data    *PortalLinkResponse `json:"data,omitempty"`
}

func (u *UpdatePortalLinkResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdatePortalLinkResponseBody) GetStatus() *bool {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdatePortalLinkResponseBody) GetData() *PortalLinkResponse {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdatePortalLinkResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Accepted
	Object *UpdatePortalLinkResponseBody
}

func (u *UpdatePortalLinkResponse) GetHTTPMeta() HTTPMetadata {
	if u == nil {
		return HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePortalLinkResponse) GetObject() *UpdatePortalLinkResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
