// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type UpdateEventTypeRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Event Type ID
	EventTypeID string `pathParam:"style=simple,explode=false,name=eventTypeID"`
	// Event Type Details
	UpdateEventType UpdateEventType `request:"mediaType=application/json"`
}

func (u *UpdateEventTypeRequest) GetProjectID() string {
	if u == nil {
		return ""
	}
	return u.ProjectID
}

func (u *UpdateEventTypeRequest) GetEventTypeID() string {
	if u == nil {
		return ""
	}
	return u.EventTypeID
}

func (u *UpdateEventTypeRequest) GetUpdateEventType() UpdateEventType {
	if u == nil {
		return UpdateEventType{}
	}
	return u.UpdateEventType
}

// UpdateEventTypeNotFoundError - Not Found
type UpdateEventTypeNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateEventTypeNotFoundError{}

func (e *UpdateEventTypeNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateEventTypeUnauthorizedError - Unauthorized
type UpdateEventTypeUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateEventTypeUnauthorizedError{}

func (e *UpdateEventTypeUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateEventTypeBadRequestError - Bad Request
type UpdateEventTypeBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateEventTypeBadRequestError{}

func (e *UpdateEventTypeBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateEventTypeResponseBody - Created
type UpdateEventTypeResponseBody struct {
	Message *string            `json:"message,omitempty"`
	Status  *bool              `json:"status,omitempty"`
	Data    *EventTypeResponse `json:"data,omitempty"`
}

func (u *UpdateEventTypeResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateEventTypeResponseBody) GetStatus() *bool {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateEventTypeResponseBody) GetData() *EventTypeResponse {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateEventTypeResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// Created
	Object *UpdateEventTypeResponseBody
}

func (u *UpdateEventTypeResponse) GetHTTPMeta() HTTPMetadata {
	if u == nil {
		return HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateEventTypeResponse) GetObject() *UpdateEventTypeResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
