// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
)

type UpdateFilterRequestRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Subscription ID
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionID"`
	// Filter ID
	FilterID string `pathParam:"style=simple,explode=false,name=filterID"`
	// Updated filter
	UpdateFilterRequest UpdateFilterRequest `request:"mediaType=application/json"`
}

func (u *UpdateFilterRequestRequest) GetProjectID() string {
	if u == nil {
		return ""
	}
	return u.ProjectID
}

func (u *UpdateFilterRequestRequest) GetSubscriptionID() string {
	if u == nil {
		return ""
	}
	return u.SubscriptionID
}

func (u *UpdateFilterRequestRequest) GetFilterID() string {
	if u == nil {
		return ""
	}
	return u.FilterID
}

func (u *UpdateFilterRequestRequest) GetUpdateFilterRequest() UpdateFilterRequest {
	if u == nil {
		return UpdateFilterRequest{}
	}
	return u.UpdateFilterRequest
}

// UpdateFilterNotFoundError - Not Found
type UpdateFilterNotFoundError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateFilterNotFoundError{}

func (e *UpdateFilterNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateFilterUnauthorizedError - Unauthorized
type UpdateFilterUnauthorizedError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateFilterUnauthorizedError{}

func (e *UpdateFilterUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateFilterBadRequestError - Bad Request
type UpdateFilterBadRequestError struct {
	Message  *string      `json:"message,omitempty"`
	Status   *bool        `json:"status,omitempty"`
	Data     *Object      `json:"data,omitempty"`
	HTTPMeta HTTPMetadata `json:"-"`
}

var _ error = &UpdateFilterBadRequestError{}

func (e *UpdateFilterBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateFilterResponseBody - OK
type UpdateFilterResponseBody struct {
	Message *string         `json:"message,omitempty"`
	Status  *bool           `json:"status,omitempty"`
	Data    *FilterResponse `json:"data,omitempty"`
}

func (u *UpdateFilterResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateFilterResponseBody) GetStatus() *bool {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateFilterResponseBody) GetData() *FilterResponse {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateFilterResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *UpdateFilterResponseBody
}

func (u *UpdateFilterResponse) GetHTTPMeta() HTTPMetadata {
	if u == nil {
		return HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateFilterResponse) GetObject() *UpdateFilterResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
