// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

type VerifierConfig struct {
	APIKey    *APIKey      `json:"api_key,omitempty"`
	BasicAuth *BasicAuth   `json:"basic_auth,omitempty"`
	Hmac      *HMac        `json:"hmac,omitempty"`
	Type      VerifierType `json:"type"`
}

func (v *VerifierConfig) GetAPIKey() *APIKey {
	if v == nil {
		return nil
	}
	return v.APIKey
}

func (v *VerifierConfig) GetBasicAuth() *BasicAuth {
	if v == nil {
		return nil
	}
	return v.BasicAuth
}

func (v *VerifierConfig) GetHmac() *HMac {
	if v == nil {
		return nil
	}
	return v.Hmac
}

func (v *VerifierConfig) GetType() VerifierType {
	if v == nil {
		return VerifierType("")
	}
	return v.Type
}
