// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package convoy

import (
	"encoding/json"
	"fmt"
)

type VerifierType string

const (
	VerifierTypeNoop      VerifierType = "noop"
	VerifierTypeHmac      VerifierType = "hmac"
	VerifierTypeBasicAuth VerifierType = "basic_auth"
	VerifierTypeAPIKey    VerifierType = "api_key"
)

func (e VerifierType) ToPointer() *VerifierType {
	return &e
}
func (e *VerifierType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "noop":
		fallthrough
	case "hmac":
		fallthrough
	case "basic_auth":
		fallthrough
	case "api_key":
		*e = VerifierType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VerifierType: %v", v)
	}
}
