// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/frain-dev/convoy/models/components"
)

type CreateEndpointEventRequest struct {
	// Project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=projectID"`
	// Event Details
	ModelsCreateEvent components.ModelsCreateEvent `request:"mediaType=application/json"`
}

func (o *CreateEndpointEventRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateEndpointEventRequest) GetModelsCreateEvent() components.ModelsCreateEvent {
	if o == nil {
		return components.ModelsCreateEvent{}
	}
	return o.ModelsCreateEvent
}

// CreateEndpointEventResponseBody - Created
type CreateEndpointEventResponseBody struct {
	Message *string                  `json:"message,omitempty"`
	Status  *bool                    `json:"status,omitempty"`
	Data    *components.HandlersStub `json:"data,omitempty"`
}

func (o *CreateEndpointEventResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateEndpointEventResponseBody) GetStatus() *bool {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateEndpointEventResponseBody) GetData() *components.HandlersStub {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateEndpointEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Object *CreateEndpointEventResponseBody
}

func (o *CreateEndpointEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEndpointEventResponse) GetObject() *CreateEndpointEventResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
