// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/frain-dev/convoy/models/components"
)

// NotFoundError - Not Found
type NotFoundError struct {
	Message  *string                  `json:"message,omitempty"`
	Status   *bool                    `json:"status,omitempty"`
	Data     *components.HandlersStub `json:"data,omitempty"`
	HTTPMeta components.HTTPMetadata  `json:"-"`
}

var _ error = &NotFoundError{}

func (e *NotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UnauthorizedError - Unauthorized
type UnauthorizedError struct {
	Message  *string                  `json:"message,omitempty"`
	Status   *bool                    `json:"status,omitempty"`
	Data     *components.HandlersStub `json:"data,omitempty"`
	HTTPMeta components.HTTPMetadata  `json:"-"`
}

var _ error = &UnauthorizedError{}

func (e *UnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BadRequestError - Bad Request
type BadRequestError struct {
	Message  *string                  `json:"message,omitempty"`
	Status   *bool                    `json:"status,omitempty"`
	Data     *components.HandlersStub `json:"data,omitempty"`
	HTTPMeta components.HTTPMetadata  `json:"-"`
}

var _ error = &BadRequestError{}

func (e *BadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
